package models

import (
	"github.com/google/uuid"
	"github.com/juevigrace/diva-server/internal/models/responses"
	"github.com/juevigrace/diva-server/storage"
)

type PermissionAction int

const (
	PERMISSION_NONE PermissionAction = iota

	PERMISSION_USERS_READ
	PERMISSION_USERS_WRITE
	PERMISSION_USERS_EMAIL_WRITE
	PERMISSION_USERS_PHONE_WRITE
	PERMISSION_USERS_USERNAME_WRITE
	PERMISSION_USERS_PASSWORD_WRITE
	PERMISSION_USERS_ROLE_WRITE
	PERMISSION_USERS_VERIFIED_WRITE
	PERMISSION_USERS_RESTORE_WRITE

	PERMISSION_USERS_PROFILE_READ
	PERMISSION_USERS_PROFILE_WRITE

	PERMISSION_USERS_PREFERENCES_READ
	PERMISSION_USERS_PREFERENCES_WRITE

	PERMISSION_SESSIONS_READ
	PERMISSION_SESSIONS_WRITE

	PERMISSION_ACTIONS_READ
	PERMISSION_ACTIONS_WRITE

	PERMISSION_USER_PERMISSIONS_READ
	PERMISSION_USER_PERMISSIONS_WRITE

	PERMISSION_PERMISSIONS_READ
	PERMISSION_PERMISSIONS_WRITE

	PERMISSION_OWNERSHIP_BYPASS
)

type Permission struct {
	ID          uuid.UUID
	Name        string
	Description string
	Action      PermissionAction
	RoleLevel   Role
	CreatedAt   int64
	UpdatedAt   int64
	DeletedAt   *int64
}

func (p *Permission) Response() *responses.PermissionResponse {
	return &responses.PermissionResponse{
		ID:          p.ID.String(),
		Name:        p.Name,
		Description: p.Description,
		Action:      p.Action.String(),
		RoleLevel:   p.RoleLevel.String(),
		CreatedAt:   p.CreatedAt,
		UpdatedAt:   p.UpdatedAt,
	}
}

func (p *Permission) DBUpdate() *storage.UpdatePermissionParams {
	return &storage.UpdatePermissionParams{
		ID:          p.ID,
		Name:        p.Name,
		Description: p.Description,
	}
}

func PermissionFromDB(row *storage.DivaPermission) *Permission {
	return &Permission{
		ID:          row.ID,
		Name:        row.Name,
		Description: row.Description,
		Action:      PermissionActionFromString(row.Action),
		RoleLevel:   RoleFromDB(row.RoleLevel),
		CreatedAt:   row.CreatedAt,
		UpdatedAt:   row.UpdatedAt,
		DeletedAt:   row.DeletedAt,
	}
}

func (p PermissionAction) String() string {
	switch p {
	case PERMISSION_USERS_READ:
		return "PERMISSION_USERS_READ"
	case PERMISSION_USERS_WRITE:
		return "PERMISSION_USERS_WRITE"
	case PERMISSION_USERS_EMAIL_WRITE:
		return "PERMISSION_USERS_EMAIL_UPDATE"
	case PERMISSION_USERS_PHONE_WRITE:
		return "PERMISSION_USERS_PHONE_UPDATE"
	case PERMISSION_USERS_USERNAME_WRITE:
		return "PERMISSION_USERS_USERNAME_UPDATE"
	case PERMISSION_USERS_PASSWORD_WRITE:
		return "PERMISSION_USERS_PASSWORD_UPDATE"
	case PERMISSION_USERS_ROLE_WRITE:
		return "PERMISSION_USERS_ROLE_UPDATE"
	case PERMISSION_USERS_VERIFIED_WRITE:
		return "PERMISSION_USERS_VERIFIED_UPDATE"
	case PERMISSION_USERS_RESTORE_WRITE:
		return "PERMISSION_USERS_RESTORE_WRITE"
	case PERMISSION_USERS_PROFILE_READ:
		return "PERMISSION_USERS_PROFILE_READ"
	case PERMISSION_USERS_PROFILE_WRITE:
		return "PERMISSION_USERS_PROFILE_CREATE"
	case PERMISSION_USERS_PREFERENCES_READ:
		return "PERMISSION_USERS_PREFERENCES_READ"
	case PERMISSION_USERS_PREFERENCES_WRITE:
		return "PERMISSION_USERS_PREFERENCES_CREATE"
	case PERMISSION_SESSIONS_READ:
		return "PERMISSION_SESSIONS_READ"
	case PERMISSION_SESSIONS_WRITE:
		return "PERMISSION_SESSIONS_WRITE"
	case PERMISSION_ACTIONS_READ:
		return "PERMISSION_ACTIONS_READ"
	case PERMISSION_ACTIONS_WRITE:
		return "PERMISSION_ACTIONS_WRITE"
	case PERMISSION_USER_PERMISSIONS_READ:
		return "PERMISSION_USER_PERMISSIONS_READ"
	case PERMISSION_USER_PERMISSIONS_WRITE:
		return "PERMISSION_USER_PERMISSIONS_WRITE"
	case PERMISSION_PERMISSIONS_READ:
		return "PERMISSION_PERMISSIONS_READ"
	case PERMISSION_PERMISSIONS_WRITE:
		return "PERMISSION_PERMISSIONS_WRITE"
	case PERMISSION_OWNERSHIP_BYPASS:
		return "PERMISSION_OWNERSHIP_BYPASS"
	default:
		return "PERMISSION_NONE"
	}
}

func PermissionActionFromString(s string) PermissionAction {
	switch s {
	case "PERMISSION_USERS_READ":
		return PERMISSION_USERS_READ
	case "PERMISSION_USERS_WRITE":
		return PERMISSION_USERS_WRITE
	case "PERMISSION_USERS_EMAIL_UPDATE":
		return PERMISSION_USERS_EMAIL_WRITE
	case "PERMISSION_USERS_PHONE_UPDATE":
		return PERMISSION_USERS_PHONE_WRITE
	case "PERMISSION_USERS_USERNAME_UPDATE":
		return PERMISSION_USERS_USERNAME_WRITE
	case "PERMISSION_USERS_PASSWORD_UPDATE":
		return PERMISSION_USERS_PASSWORD_WRITE
	case "PERMISSION_USERS_ROLE_UPDATE":
		return PERMISSION_USERS_ROLE_WRITE
	case "PERMISSION_USERS_VERIFIED_UPDATE":
		return PERMISSION_USERS_VERIFIED_WRITE
	case "PERMISSION_USERS_RESTORE_WRITE":
		return PERMISSION_USERS_RESTORE_WRITE
	case "PERMISSION_USERS_PROFILE_READ":
		return PERMISSION_USERS_PROFILE_READ
	case "PERMISSION_USERS_PROFILE_CREATE":
		return PERMISSION_USERS_PROFILE_WRITE
	case "PERMISSION_USERS_PREFERENCES_READ":
		return PERMISSION_USERS_PREFERENCES_READ
	case "PERMISSION_USERS_PREFERENCES_CREATE":
		return PERMISSION_USERS_PREFERENCES_WRITE
	case "PERMISSION_SESSIONS_READ":
		return PERMISSION_SESSIONS_READ
	case "PERMISSION_SESSIONS_WRITE":
		return PERMISSION_SESSIONS_WRITE
	case "PERMISSION_ACTIONS_READ":
		return PERMISSION_ACTIONS_READ
	case "PERMISSION_ACTIONS_WRITE":
		return PERMISSION_ACTIONS_WRITE
	case "PERMISSION_USER_PERMISSIONS_READ":
		return PERMISSION_USER_PERMISSIONS_READ
	case "PERMISSION_USER_PERMISSIONS_WRITE":
		return PERMISSION_USER_PERMISSIONS_WRITE
	case "PERMISSION_PERMISSIONS_READ":
		return PERMISSION_PERMISSIONS_READ
	case "PERMISSION_PERMISSIONS_WRITE":
		return PERMISSION_PERMISSIONS_WRITE
	case "PERMISSION_OWNERSHIP_BYPASS":
		return PERMISSION_OWNERSHIP_BYPASS
	default:
		return PERMISSION_NONE
	}
}
