// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: chat.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countChat = `-- name: CountChat :one
SELECT COUNT(*)
FROM diva_chat
WHERE deleted_at IS NULL
`

func (q *Queries) CountChat(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countChat)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createChat = `-- name: CreateChat :exec
INSERT INTO diva_chat (id, created_by, chat_type, name, description, avatar)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateChatParams struct {
	ID          pgtype.UUID
	CreatedBy   pgtype.UUID
	ChatType    ChatTypeType
	Name        string
	Description string
	Avatar      pgtype.UUID
}

func (q *Queries) CreateChat(ctx context.Context, arg CreateChatParams) error {
	_, err := q.db.Exec(ctx, createChat,
		arg.ID,
		arg.CreatedBy,
		arg.ChatType,
		arg.Name,
		arg.Description,
		arg.Avatar,
	)
	return err
}

const deleteChat = `-- name: DeleteChat :exec
UPDATE diva_chat 
SET deleted_at = NOW() 
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) DeleteChat(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteChat, id)
	return err
}

const getChatByID = `-- name: GetChatByID :one
SELECT 
  diva_chat.id,
  diva_chat.chat_type AS chat_type,
  diva_chat.name,
  diva_chat.description,
  diva_chat.avatar,
  diva_chat.created_by AS created_by,
  diva_chat.created_at AS created_at,
  diva_chat.updated_at AS updated_at,
  diva_chat.deleted_at AS deleted_at
FROM diva_chat
LEFT JOIN diva_chat_participant
ON diva_chat.id = diva_chat_participant.chat_id
LEFT JOIN diva_user
ON diva_chat_participant.user_id = diva_user.id
LEFT JOIN diva_media
ON diva_chat.avatar = diva_media.id
LEFT JOIN diva_media_tag
ON diva_media.id = diva_media_tag.media_id
LEFT JOIN diva_tag
ON diva_media_tag.tag_id = diva_tag.id
WHERE diva_chat.id = $1 AND diva_chat.deleted_at IS NULL
`

type GetChatByIDRow struct {
	ID          pgtype.UUID
	ChatType    ChatTypeType
	Name        string
	Description string
	Avatar      pgtype.UUID
	CreatedBy   pgtype.UUID
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	DeletedAt   pgtype.Timestamptz
}

func (q *Queries) GetChatByID(ctx context.Context, id pgtype.UUID) (GetChatByIDRow, error) {
	row := q.db.QueryRow(ctx, getChatByID, id)
	var i GetChatByIDRow
	err := row.Scan(
		&i.ID,
		&i.ChatType,
		&i.Name,
		&i.Description,
		&i.Avatar,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listChats = `-- name: ListChats :many
SELECT 
  id,
  chat_type,
  name,
  description,
  avatar,
  created_by,
  created_at,
  updated_at,
  deleted_at
FROM diva_chat
WHERE deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListChatsParams struct {
	Limit  int32
	Offset int32
}

type ListChatsRow struct {
	ID          pgtype.UUID
	ChatType    ChatTypeType
	Name        string
	Description string
	Avatar      pgtype.UUID
	CreatedBy   pgtype.UUID
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	DeletedAt   pgtype.Timestamptz
}

func (q *Queries) ListChats(ctx context.Context, arg ListChatsParams) ([]ListChatsRow, error) {
	rows, err := q.db.Query(ctx, listChats, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChatsRow
	for rows.Next() {
		var i ListChatsRow
		if err := rows.Scan(
			&i.ID,
			&i.ChatType,
			&i.Name,
			&i.Description,
			&i.Avatar,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateChat = `-- name: UpdateChat :exec
UPDATE diva_chat 
SET name = $1, description = $2, avatar = $3, updated_at = NOW()
WHERE id = $4 AND deleted_at IS NULL
`

type UpdateChatParams struct {
	Name        string
	Description string
	Avatar      pgtype.UUID
	ID          pgtype.UUID
}

func (q *Queries) UpdateChat(ctx context.Context, arg UpdateChatParams) error {
	_, err := q.db.Exec(ctx, updateChat,
		arg.Name,
		arg.Description,
		arg.Avatar,
		arg.ID,
	)
	return err
}
