// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: chat_participant.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createChatParticipant = `-- name: CreateChatParticipant :exec
INSERT INTO diva_chat_participant (chat_id, user_id, role, added_by)
VALUES ($1, $2, $3, $4)
`

type CreateChatParticipantParams struct {
	ChatID  pgtype.UUID
	UserID  pgtype.UUID
	Role    ParticipantRoleType
	AddedBy pgtype.UUID
}

func (q *Queries) CreateChatParticipant(ctx context.Context, arg CreateChatParticipantParams) error {
	_, err := q.db.Exec(ctx, createChatParticipant,
		arg.ChatID,
		arg.UserID,
		arg.Role,
		arg.AddedBy,
	)
	return err
}

const deleteChatParticipant = `-- name: DeleteChatParticipant :exec
DELETE FROM diva_chat_participant 
WHERE chat_id = $1 AND user_id = $2
`

type DeleteChatParticipantParams struct {
	ChatID pgtype.UUID
	UserID pgtype.UUID
}

func (q *Queries) DeleteChatParticipant(ctx context.Context, arg DeleteChatParticipantParams) error {
	_, err := q.db.Exec(ctx, deleteChatParticipant, arg.ChatID, arg.UserID)
	return err
}

const updateChatParticipant = `-- name: UpdateChatParticipant :exec
UPDATE diva_chat_participant 
SET role = $1, last_read_at = $2
WHERE chat_id = $3 AND user_id = $4
`

type UpdateChatParticipantParams struct {
	Role       ParticipantRoleType
	LastReadAt pgtype.Timestamptz
	ChatID     pgtype.UUID
	UserID     pgtype.UUID
}

func (q *Queries) UpdateChatParticipant(ctx context.Context, arg UpdateChatParticipantParams) error {
	_, err := q.db.Exec(ctx, updateChatParticipant,
		arg.Role,
		arg.LastReadAt,
		arg.ChatID,
		arg.UserID,
	)
	return err
}
