// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: collection.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countCollection = `-- name: CountCollection :one
SELECT COUNT(*)
FROM diva_collection
WHERE deleted_at IS NULL
`

func (q *Queries) CountCollection(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countCollection)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCollection = `-- name: CreateCollection :exec
INSERT INTO diva_collection (id, owner, cover_media_id, name, description, collection_type, visibility)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateCollectionParams struct {
	ID             pgtype.UUID
	Owner          pgtype.UUID
	CoverMediaID   pgtype.UUID
	Name           string
	Description    string
	CollectionType CollectionTypeType
	Visibility     VisibilityType
}

func (q *Queries) CreateCollection(ctx context.Context, arg CreateCollectionParams) error {
	_, err := q.db.Exec(ctx, createCollection,
		arg.ID,
		arg.Owner,
		arg.CoverMediaID,
		arg.Name,
		arg.Description,
		arg.CollectionType,
		arg.Visibility,
	)
	return err
}

const deleteCollection = `-- name: DeleteCollection :exec
UPDATE diva_collection 
SET deleted_at = NOW() 
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) DeleteCollection(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCollection, id)
	return err
}

const getCollectionByID = `-- name: GetCollectionByID :one
SELECT id, owner, cover_media_id, name, description, collection_type, visibility, created_at, updated_at, deleted_at FROM diva_collection 
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetCollectionByID(ctx context.Context, id pgtype.UUID) (DivaCollection, error) {
	row := q.db.QueryRow(ctx, getCollectionByID, id)
	var i DivaCollection
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.CoverMediaID,
		&i.Name,
		&i.Description,
		&i.CollectionType,
		&i.Visibility,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listCollections = `-- name: ListCollections :many
SELECT id, owner, cover_media_id, name, description, collection_type, visibility, created_at, updated_at, deleted_at FROM diva_collection 
WHERE deleted_at IS NULL 
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListCollectionsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListCollections(ctx context.Context, arg ListCollectionsParams) ([]DivaCollection, error) {
	rows, err := q.db.Query(ctx, listCollections, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DivaCollection
	for rows.Next() {
		var i DivaCollection
		if err := rows.Scan(
			&i.ID,
			&i.Owner,
			&i.CoverMediaID,
			&i.Name,
			&i.Description,
			&i.CollectionType,
			&i.Visibility,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCollection = `-- name: UpdateCollection :exec
UPDATE diva_collection 
SET cover_media_id = $1, name = $2, description = $3, visibility = $4, updated_at = NOW()
WHERE id = $5 AND deleted_at IS NULL
`

type UpdateCollectionParams struct {
	CoverMediaID pgtype.UUID
	Name         string
	Description  string
	Visibility   VisibilityType
	ID           pgtype.UUID
}

func (q *Queries) UpdateCollection(ctx context.Context, arg UpdateCollectionParams) error {
	_, err := q.db.Exec(ctx, updateCollection,
		arg.CoverMediaID,
		arg.Name,
		arg.Description,
		arg.Visibility,
		arg.ID,
	)
	return err
}
