// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: collection_media.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCollectionMedia = `-- name: CreateCollectionMedia :exec
INSERT INTO diva_collection_media (collection_id, media_id, position, added_by, score)
VALUES ($1, $2, $3, $4, $5)
`

type CreateCollectionMediaParams struct {
	CollectionID pgtype.UUID
	MediaID      pgtype.UUID
	Position     int32
	AddedBy      pgtype.UUID
	Score        pgtype.Numeric
}

func (q *Queries) CreateCollectionMedia(ctx context.Context, arg CreateCollectionMediaParams) error {
	_, err := q.db.Exec(ctx, createCollectionMedia,
		arg.CollectionID,
		arg.MediaID,
		arg.Position,
		arg.AddedBy,
		arg.Score,
	)
	return err
}

const deleteCollectionMedia = `-- name: DeleteCollectionMedia :exec
DELETE FROM diva_collection_media
WHERE collection_id = $1 AND media_id = $2
`

type DeleteCollectionMediaParams struct {
	CollectionID pgtype.UUID
	MediaID      pgtype.UUID
}

func (q *Queries) DeleteCollectionMedia(ctx context.Context, arg DeleteCollectionMediaParams) error {
	_, err := q.db.Exec(ctx, deleteCollectionMedia, arg.CollectionID, arg.MediaID)
	return err
}

const updateCollectionMedia = `-- name: UpdateCollectionMedia :exec
UPDATE diva_collection_media
SET position = $1, score = $2
WHERE collection_id = $3 AND media_id = $4
`

type UpdateCollectionMediaParams struct {
	Position     int32
	Score        pgtype.Numeric
	CollectionID pgtype.UUID
	MediaID      pgtype.UUID
}

func (q *Queries) UpdateCollectionMedia(ctx context.Context, arg UpdateCollectionMediaParams) error {
	_, err := q.db.Exec(ctx, updateCollectionMedia,
		arg.Position,
		arg.Score,
		arg.CollectionID,
		arg.MediaID,
	)
	return err
}
