// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: email_verification_tokens.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const create = `-- name: Create :exec
INSERT INTO diva_email_verification_tokens (user_id, token, expires_at, created_at)
VALUES ($1, $2, $3, $4)
`

type CreateParams struct {
	UserID    pgtype.UUID
	Token     string
	ExpiresAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) Create(ctx context.Context, arg CreateParams) error {
	_, err := q.db.Exec(ctx, create,
		arg.UserID,
		arg.Token,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	return err
}

const deleteByToken = `-- name: DeleteByToken :exec
delete from diva_email_verification_tokens
where token = $1
`

func (q *Queries) DeleteByToken(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, deleteByToken, token)
	return err
}

const getByToken = `-- name: GetByToken :one
select user_id, token, expires_at, created_at
from diva_email_verification_tokens
where token = $1
`

func (q *Queries) GetByToken(ctx context.Context, token string) (DivaEmailVerificationToken, error) {
	row := q.db.QueryRow(ctx, getByToken, token)
	var i DivaEmailVerificationToken
	err := row.Scan(
		&i.UserID,
		&i.Token,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}
