// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: email_verification_tokens.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEmailVerificationToken = `-- name: CreateEmailVerificationToken :exec
INSERT INTO diva_email_verification_tokens(
    user_id,
    token,
    expires_at
) VALUES ($1, $2, $3)
`

type CreateEmailVerificationTokenParams struct {
	UserID    pgtype.UUID
	Token     string
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateEmailVerificationToken(ctx context.Context, arg CreateEmailVerificationTokenParams) error {
	_, err := q.db.Exec(ctx, createEmailVerificationToken, arg.UserID, arg.Token, arg.ExpiresAt)
	return err
}

const deleteEmailVerificationToken = `-- name: DeleteEmailVerificationToken :exec
DELETE FROM diva_email_verification_tokens
WHERE user_id = $1
`

func (q *Queries) DeleteEmailVerificationToken(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteEmailVerificationToken, userID)
	return err
}

const deleteEmailVerificationTokenByToken = `-- name: DeleteEmailVerificationTokenByToken :exec
DELETE FROM diva_email_verification_tokens
WHERE token = $1
`

func (q *Queries) DeleteEmailVerificationTokenByToken(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, deleteEmailVerificationTokenByToken, token)
	return err
}

const getEmailVerificationTokenByToken = `-- name: GetEmailVerificationTokenByToken :one
SELECT
    user_id AS user_id,
    token,
    expires_at AS expires_at,
    created_at AS created_at,
    used_at AS used_at
FROM diva_email_verification_tokens
WHERE token = $1
`

func (q *Queries) GetEmailVerificationTokenByToken(ctx context.Context, token string) (DivaEmailVerificationToken, error) {
	row := q.db.QueryRow(ctx, getEmailVerificationTokenByToken, token)
	var i DivaEmailVerificationToken
	err := row.Scan(
		&i.UserID,
		&i.Token,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UsedAt,
	)
	return i, err
}

const getEmailVerificationTokenByUserID = `-- name: GetEmailVerificationTokenByUserID :one
SELECT
    user_id AS user_id,
    token,
    expires_at AS expires_at,
    created_at AS created_at,
    used_at AS used_at
FROM diva_email_verification_tokens
WHERE user_id = $1
`

func (q *Queries) GetEmailVerificationTokenByUserID(ctx context.Context, userID pgtype.UUID) (DivaEmailVerificationToken, error) {
	row := q.db.QueryRow(ctx, getEmailVerificationTokenByUserID, userID)
	var i DivaEmailVerificationToken
	err := row.Scan(
		&i.UserID,
		&i.Token,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UsedAt,
	)
	return i, err
}

const markEmailVerificationTokenAsUsed = `-- name: MarkEmailVerificationTokenAsUsed :exec
UPDATE diva_email_verification_tokens
SET used_at = NOW()
WHERE user_id = $1
`

func (q *Queries) MarkEmailVerificationTokenAsUsed(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markEmailVerificationTokenAsUsed, userID)
	return err
}
