// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: email_verification_tokens.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createVerification = `-- name: CreateVerification :exec
INSERT INTO diva_email_verification_tokens (user_id, action_id, token, expires_at)
VALUES ($1, $2, $3, $4)
`

type CreateVerificationParams struct {
	UserID    pgtype.UUID
	ActionID  pgtype.UUID
	Token     string
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateVerification(ctx context.Context, arg CreateVerificationParams) error {
	_, err := q.db.Exec(ctx, createVerification,
		arg.UserID,
		arg.ActionID,
		arg.Token,
		arg.ExpiresAt,
	)
	return err
}

const deleteByToken = `-- name: DeleteByToken :exec
delete from diva_email_verification_tokens
where token = $1
`

func (q *Queries) DeleteByToken(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, deleteByToken, token)
	return err
}

const getVerificationByToken = `-- name: GetVerificationByToken :one
select ev.user_id, ev.token, ev.expires_at, ev.created_at, up.action_name
from diva_email_verification_tokens as ev
left join diva_user_pending_actions as up on up.id = ev.action_id
where token = $1
`

type GetVerificationByTokenRow struct {
	UserID     pgtype.UUID
	Token      string
	ExpiresAt  pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
	ActionName pgtype.Text
}

func (q *Queries) GetVerificationByToken(ctx context.Context, token string) (GetVerificationByTokenRow, error) {
	row := q.db.QueryRow(ctx, getVerificationByToken, token)
	var i GetVerificationByTokenRow
	err := row.Scan(
		&i.UserID,
		&i.Token,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.ActionName,
	)
	return i, err
}
