// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: follow.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createFollow = `-- name: CreateFollow :exec
INSERT INTO diva_follow (user_id, followed)
VALUES ($1, $2)
`

type CreateFollowParams struct {
	UserID   pgtype.UUID
	Followed pgtype.UUID
}

func (q *Queries) CreateFollow(ctx context.Context, arg CreateFollowParams) error {
	_, err := q.db.Exec(ctx, createFollow, arg.UserID, arg.Followed)
	return err
}

const deleteFollow = `-- name: DeleteFollow :exec
DELETE FROM diva_follow
WHERE user_id = $1 AND followed = $2
`

type DeleteFollowParams struct {
	UserID   pgtype.UUID
	Followed pgtype.UUID
}

func (q *Queries) DeleteFollow(ctx context.Context, arg DeleteFollowParams) error {
	_, err := q.db.Exec(ctx, deleteFollow, arg.UserID, arg.Followed)
	return err
}
