// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: interactions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCollectionComment = `-- name: CreateCollectionComment :exec

INSERT INTO diva_collection_comment (interaction_id, reply_to, content)
VALUES ($1, $2, $3)
`

type CreateCollectionCommentParams struct {
	InteractionID pgtype.UUID
	ReplyTo       pgtype.UUID
	Content       string
}

// Collection Comments
func (q *Queries) CreateCollectionComment(ctx context.Context, arg CreateCollectionCommentParams) error {
	_, err := q.db.Exec(ctx, createCollectionComment, arg.InteractionID, arg.ReplyTo, arg.Content)
	return err
}

const createCollectionInteraction = `-- name: CreateCollectionInteraction :exec

INSERT INTO diva_collection_interaction (id, collection_id, user_id, reaction_type)
VALUES ($1, $2, $3, $4)
`

type CreateCollectionInteractionParams struct {
	ID           pgtype.UUID
	CollectionID pgtype.UUID
	UserID       pgtype.UUID
	ReactionType string
}

// Collection Interactions
func (q *Queries) CreateCollectionInteraction(ctx context.Context, arg CreateCollectionInteractionParams) error {
	_, err := q.db.Exec(ctx, createCollectionInteraction,
		arg.ID,
		arg.CollectionID,
		arg.UserID,
		arg.ReactionType,
	)
	return err
}

const createCollectionShare = `-- name: CreateCollectionShare :exec

INSERT INTO diva_collection_share (interaction_id, share_type, caption)
VALUES ($1, $2, $3)
`

type CreateCollectionShareParams struct {
	InteractionID pgtype.UUID
	ShareType     string
	Caption       string
}

// Collection Shares
func (q *Queries) CreateCollectionShare(ctx context.Context, arg CreateCollectionShareParams) error {
	_, err := q.db.Exec(ctx, createCollectionShare, arg.InteractionID, arg.ShareType, arg.Caption)
	return err
}

const createMessageInteraction = `-- name: CreateMessageInteraction :exec

INSERT INTO diva_message_interaction (id, message_id, user_id, reaction_type)
VALUES ($1, $2, $3, $4)
`

type CreateMessageInteractionParams struct {
	ID           pgtype.UUID
	MessageID    pgtype.UUID
	UserID       pgtype.UUID
	ReactionType string
}

// Message Interactions
func (q *Queries) CreateMessageInteraction(ctx context.Context, arg CreateMessageInteractionParams) error {
	_, err := q.db.Exec(ctx, createMessageInteraction,
		arg.ID,
		arg.MessageID,
		arg.UserID,
		arg.ReactionType,
	)
	return err
}

const createPostComment = `-- name: CreatePostComment :exec

INSERT INTO diva_post_comment (interaction_id, reply_to, content)
VALUES ($1, $2, $3)
`

type CreatePostCommentParams struct {
	InteractionID pgtype.UUID
	ReplyTo       pgtype.UUID
	Content       string
}

// Post Comments
func (q *Queries) CreatePostComment(ctx context.Context, arg CreatePostCommentParams) error {
	_, err := q.db.Exec(ctx, createPostComment, arg.InteractionID, arg.ReplyTo, arg.Content)
	return err
}

const createPostInteraction = `-- name: CreatePostInteraction :exec

INSERT INTO diva_post_interaction (id, post_id, user_id, reaction_type)
VALUES ($1, $2, $3, $4)
`

type CreatePostInteractionParams struct {
	ID           pgtype.UUID
	PostID       pgtype.UUID
	UserID       pgtype.UUID
	ReactionType string
}

// Post Interactions
func (q *Queries) CreatePostInteraction(ctx context.Context, arg CreatePostInteractionParams) error {
	_, err := q.db.Exec(ctx, createPostInteraction,
		arg.ID,
		arg.PostID,
		arg.UserID,
		arg.ReactionType,
	)
	return err
}

const createPostShare = `-- name: CreatePostShare :exec

INSERT INTO diva_post_share (interaction_id, share_type, caption)
VALUES ($1, $2, $3)
`

type CreatePostShareParams struct {
	InteractionID pgtype.UUID
	ShareType     string
	Caption       string
}

// Post Shares
func (q *Queries) CreatePostShare(ctx context.Context, arg CreatePostShareParams) error {
	_, err := q.db.Exec(ctx, createPostShare, arg.InteractionID, arg.ShareType, arg.Caption)
	return err
}

const deleteCollectionComment = `-- name: DeleteCollectionComment :exec
DELETE FROM diva_collection_comment
WHERE interaction_id = $1
`

func (q *Queries) DeleteCollectionComment(ctx context.Context, interactionID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCollectionComment, interactionID)
	return err
}

const deleteCollectionInteraction = `-- name: DeleteCollectionInteraction :exec
DELETE FROM diva_collection_interaction
WHERE id = $1
`

func (q *Queries) DeleteCollectionInteraction(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCollectionInteraction, id)
	return err
}

const deleteCollectionShare = `-- name: DeleteCollectionShare :exec
DELETE FROM diva_collection_share
WHERE interaction_id = $1
`

func (q *Queries) DeleteCollectionShare(ctx context.Context, interactionID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCollectionShare, interactionID)
	return err
}

const deleteMessageInteraction = `-- name: DeleteMessageInteraction :exec
DELETE FROM diva_message_interaction
WHERE id = $1
`

func (q *Queries) DeleteMessageInteraction(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteMessageInteraction, id)
	return err
}

const deletePostComment = `-- name: DeletePostComment :exec
DELETE FROM diva_post_comment
WHERE interaction_id = $1
`

func (q *Queries) DeletePostComment(ctx context.Context, interactionID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deletePostComment, interactionID)
	return err
}

const deletePostInteraction = `-- name: DeletePostInteraction :exec
DELETE FROM diva_post_interaction
WHERE id = $1
`

func (q *Queries) DeletePostInteraction(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deletePostInteraction, id)
	return err
}

const deletePostShare = `-- name: DeletePostShare :exec
DELETE FROM diva_post_share
WHERE interaction_id = $1
`

func (q *Queries) DeletePostShare(ctx context.Context, interactionID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deletePostShare, interactionID)
	return err
}

const updateCollectionComment = `-- name: UpdateCollectionComment :exec
UPDATE diva_collection_comment
SET content = $1, edited_at = NOW()
WHERE interaction_id = $2
`

type UpdateCollectionCommentParams struct {
	Content       string
	InteractionID pgtype.UUID
}

func (q *Queries) UpdateCollectionComment(ctx context.Context, arg UpdateCollectionCommentParams) error {
	_, err := q.db.Exec(ctx, updateCollectionComment, arg.Content, arg.InteractionID)
	return err
}

const updatePostComment = `-- name: UpdatePostComment :exec
UPDATE diva_post_comment
SET content = $1, edited_at = NOW()
WHERE interaction_id = $2
`

type UpdatePostCommentParams struct {
	Content       string
	InteractionID pgtype.UUID
}

func (q *Queries) UpdatePostComment(ctx context.Context, arg UpdatePostCommentParams) error {
	_, err := q.db.Exec(ctx, updatePostComment, arg.Content, arg.InteractionID)
	return err
}
