// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: media_tag.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMediaTag = `-- name: CreateMediaTag :exec
INSERT INTO diva_media_tag (media_id, tag_id)
VALUES ($1, $2)
`

type CreateMediaTagParams struct {
	MediaID pgtype.UUID
	TagID   pgtype.UUID
}

func (q *Queries) CreateMediaTag(ctx context.Context, arg CreateMediaTagParams) error {
	_, err := q.db.Exec(ctx, createMediaTag, arg.MediaID, arg.TagID)
	return err
}

const deleteMediaTag = `-- name: DeleteMediaTag :exec
DELETE FROM diva_media_tag 
WHERE media_id = $1 AND tag_id = $2
`

type DeleteMediaTagParams struct {
	MediaID pgtype.UUID
	TagID   pgtype.UUID
}

func (q *Queries) DeleteMediaTag(ctx context.Context, arg DeleteMediaTagParams) error {
	_, err := q.db.Exec(ctx, deleteMediaTag, arg.MediaID, arg.TagID)
	return err
}

const updateMediaTag = `-- name: UpdateMediaTag :exec
UPDATE diva_media_tag 
SET media_id = $1, tag_id = $2 
WHERE media_id = $3 AND tag_id = $4
`

type UpdateMediaTagParams struct {
	MediaID   pgtype.UUID
	TagID     pgtype.UUID
	MediaID_2 pgtype.UUID
	TagID_2   pgtype.UUID
}

func (q *Queries) UpdateMediaTag(ctx context.Context, arg UpdateMediaTagParams) error {
	_, err := q.db.Exec(ctx, updateMediaTag,
		arg.MediaID,
		arg.TagID,
		arg.MediaID_2,
		arg.TagID_2,
	)
	return err
}
