// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: media.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countMedia = `-- name: CountMedia :one
SELECT COUNT(*)
FROM diva_media
WHERE deleted_at IS NULL
`

func (q *Queries) CountMedia(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countMedia)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMedia = `-- name: CreateMedia :exec
INSERT INTO diva_media (id, submitted_by, url, alt_text, media_type, file_size, width, height, duration, visibility, sensitive_content, adult_content)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
`

type CreateMediaParams struct {
	ID               pgtype.UUID
	SubmittedBy      pgtype.UUID
	Url              string
	AltText          string
	MediaType        string
	FileSize         int64
	Width            int32
	Height           int32
	Duration         int32
	Visibility       string
	SensitiveContent bool
	AdultContent     bool
}

func (q *Queries) CreateMedia(ctx context.Context, arg CreateMediaParams) error {
	_, err := q.db.Exec(ctx, createMedia,
		arg.ID,
		arg.SubmittedBy,
		arg.Url,
		arg.AltText,
		arg.MediaType,
		arg.FileSize,
		arg.Width,
		arg.Height,
		arg.Duration,
		arg.Visibility,
		arg.SensitiveContent,
		arg.AdultContent,
	)
	return err
}

const deleteMedia = `-- name: DeleteMedia :exec
UPDATE diva_media 
SET deleted_at = NOW() 
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) DeleteMedia(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteMedia, id)
	return err
}

const getMediaByID = `-- name: GetMediaByID :one
SELECT 
  id,
  submitted_by AS submitted_by,
  url,
  alt_text AS alt_text,
  media_type AS media_type,
  file_size AS file_size,
  width,
  height,
  duration,
  visibility,
  sensitive_content AS sensitive_content,
  adult_content AS adult_content,
  published_at AS published_at,
  created_at AS created_at,
  updated_at AS updated_at,
  deleted_at AS deleted_at
FROM diva_media
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetMediaByID(ctx context.Context, id pgtype.UUID) (DivaMedium, error) {
	row := q.db.QueryRow(ctx, getMediaByID, id)
	var i DivaMedium
	err := row.Scan(
		&i.ID,
		&i.SubmittedBy,
		&i.Url,
		&i.AltText,
		&i.MediaType,
		&i.FileSize,
		&i.Width,
		&i.Height,
		&i.Duration,
		&i.Visibility,
		&i.SensitiveContent,
		&i.AdultContent,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listMedia = `-- name: ListMedia :many
SELECT 
  id,
  submitted_by AS submitted_by,
  url,
  alt_text AS alt_text,
  media_type AS media_type,
  file_size AS file_size,
  width,
  height,
  duration,
  visibility,
  sensitive_content AS sensitive_content,
  adult_content AS adult_content,
  published_at AS published_at,
  created_at AS created_at,
  updated_at AS updated_at,
  deleted_at AS deleted_at
FROM diva_media
WHERE deleted_at IS NULL 
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListMediaParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListMedia(ctx context.Context, arg ListMediaParams) ([]DivaMedium, error) {
	rows, err := q.db.Query(ctx, listMedia, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DivaMedium
	for rows.Next() {
		var i DivaMedium
		if err := rows.Scan(
			&i.ID,
			&i.SubmittedBy,
			&i.Url,
			&i.AltText,
			&i.MediaType,
			&i.FileSize,
			&i.Width,
			&i.Height,
			&i.Duration,
			&i.Visibility,
			&i.SensitiveContent,
			&i.AdultContent,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMedia = `-- name: UpdateMedia :exec
UPDATE diva_media 
SET url = $1, alt_text = $2, media_type = $3, file_size = $4, width = $5, height = $6, duration = $7, visibility = $8, sensitive_content = $9, adult_content = $10, updated_at = NOW()
WHERE id = $11 AND deleted_at IS NULL
`

type UpdateMediaParams struct {
	Url              string
	AltText          string
	MediaType        string
	FileSize         int64
	Width            int32
	Height           int32
	Duration         int32
	Visibility       string
	SensitiveContent bool
	AdultContent     bool
	ID               pgtype.UUID
}

func (q *Queries) UpdateMedia(ctx context.Context, arg UpdateMediaParams) error {
	_, err := q.db.Exec(ctx, updateMedia,
		arg.Url,
		arg.AltText,
		arg.MediaType,
		arg.FileSize,
		arg.Width,
		arg.Height,
		arg.Duration,
		arg.Visibility,
		arg.SensitiveContent,
		arg.AdultContent,
		arg.ID,
	)
	return err
}
