// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: message_media.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMessageMedia = `-- name: CreateMessageMedia :exec
INSERT INTO diva_message_media (message_id, media_id)
VALUES ($1, $2)
`

type CreateMessageMediaParams struct {
	MessageID pgtype.UUID
	MediaID   pgtype.UUID
}

func (q *Queries) CreateMessageMedia(ctx context.Context, arg CreateMessageMediaParams) error {
	_, err := q.db.Exec(ctx, createMessageMedia, arg.MessageID, arg.MediaID)
	return err
}

const deleteMessageMedia = `-- name: DeleteMessageMedia :exec
DELETE FROM diva_message_media 
WHERE message_id = $1 AND media_id = $2
`

type DeleteMessageMediaParams struct {
	MessageID pgtype.UUID
	MediaID   pgtype.UUID
}

func (q *Queries) DeleteMessageMedia(ctx context.Context, arg DeleteMessageMediaParams) error {
	_, err := q.db.Exec(ctx, deleteMessageMedia, arg.MessageID, arg.MediaID)
	return err
}
