// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: message.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMessage = `-- name: CreateMessage :exec
INSERT INTO diva_message (id, chat_id, sender_id, content, message_type, reply_to_id)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateMessageParams struct {
	ID          pgtype.UUID
	ChatID      pgtype.UUID
	SenderID    pgtype.UUID
	Content     string
	MessageType string
	ReplyToID   pgtype.UUID
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) error {
	_, err := q.db.Exec(ctx, createMessage,
		arg.ID,
		arg.ChatID,
		arg.SenderID,
		arg.Content,
		arg.MessageType,
		arg.ReplyToID,
	)
	return err
}

const deleteMessage = `-- name: DeleteMessage :exec
UPDATE diva_message 
SET deleted_at = NOW() 
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) DeleteMessage(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteMessage, id)
	return err
}

const getMessageByID = `-- name: GetMessageByID :one
SELECT id, chat_id AS chat_id, sender_id AS sender_id, content, message_type AS message_type, reply_to_id AS reply_to_id, created_at AS created_at, updated_at AS updated_at, deleted_at AS deleted_at, edited_at AS edited_at FROM diva_message 
WHERE id = $1 AND deleted_at IS NULL
`

type GetMessageByIDRow struct {
	ID          pgtype.UUID
	ChatID      pgtype.UUID
	SenderID    pgtype.UUID
	Content     string
	MessageType string
	ReplyToID   pgtype.UUID
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	DeletedAt   pgtype.Timestamptz
	EditedAt    pgtype.Timestamptz
}

func (q *Queries) GetMessageByID(ctx context.Context, id pgtype.UUID) (GetMessageByIDRow, error) {
	row := q.db.QueryRow(ctx, getMessageByID, id)
	var i GetMessageByIDRow
	err := row.Scan(
		&i.ID,
		&i.ChatID,
		&i.SenderID,
		&i.Content,
		&i.MessageType,
		&i.ReplyToID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.EditedAt,
	)
	return i, err
}

const getMessagesByChat = `-- name: GetMessagesByChat :many
SELECT id, chat_id AS chat_id, sender_id AS sender_id, content, message_type AS message_type, reply_to_id AS reply_to_id, created_at AS created_at, updated_at AS updated_at, deleted_at AS deleted_at, edited_at AS edited_at FROM diva_message 
WHERE chat_id = $1 AND deleted_at IS NULL 
ORDER BY created_at ASC
`

type GetMessagesByChatRow struct {
	ID          pgtype.UUID
	ChatID      pgtype.UUID
	SenderID    pgtype.UUID
	Content     string
	MessageType string
	ReplyToID   pgtype.UUID
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	DeletedAt   pgtype.Timestamptz
	EditedAt    pgtype.Timestamptz
}

func (q *Queries) GetMessagesByChat(ctx context.Context, chatID pgtype.UUID) ([]GetMessagesByChatRow, error) {
	rows, err := q.db.Query(ctx, getMessagesByChat, chatID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMessagesByChatRow
	for rows.Next() {
		var i GetMessagesByChatRow
		if err := rows.Scan(
			&i.ID,
			&i.ChatID,
			&i.SenderID,
			&i.Content,
			&i.MessageType,
			&i.ReplyToID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.EditedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMessagesBySender = `-- name: GetMessagesBySender :many
SELECT id, chat_id AS chat_id, sender_id AS sender_id, content, message_type AS message_type, reply_to_id AS reply_to_id, created_at AS created_at, updated_at AS updated_at, deleted_at AS deleted_at, edited_at AS edited_at FROM diva_message 
WHERE sender_id = $1 AND deleted_at IS NULL 
ORDER BY created_at DESC
`

type GetMessagesBySenderRow struct {
	ID          pgtype.UUID
	ChatID      pgtype.UUID
	SenderID    pgtype.UUID
	Content     string
	MessageType string
	ReplyToID   pgtype.UUID
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	DeletedAt   pgtype.Timestamptz
	EditedAt    pgtype.Timestamptz
}

func (q *Queries) GetMessagesBySender(ctx context.Context, senderID pgtype.UUID) ([]GetMessagesBySenderRow, error) {
	rows, err := q.db.Query(ctx, getMessagesBySender, senderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMessagesBySenderRow
	for rows.Next() {
		var i GetMessagesBySenderRow
		if err := rows.Scan(
			&i.ID,
			&i.ChatID,
			&i.SenderID,
			&i.Content,
			&i.MessageType,
			&i.ReplyToID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.EditedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessages = `-- name: ListMessages :many
SELECT id, chat_id AS chat_id, sender_id AS sender_id, content, message_type AS message_type, reply_to_id AS reply_to_id, created_at AS created_at, updated_at AS updated_at, deleted_at AS deleted_at, edited_at AS edited_at FROM diva_message 
WHERE deleted_at IS NULL 
ORDER BY created_at DESC
`

type ListMessagesRow struct {
	ID          pgtype.UUID
	ChatID      pgtype.UUID
	SenderID    pgtype.UUID
	Content     string
	MessageType string
	ReplyToID   pgtype.UUID
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	DeletedAt   pgtype.Timestamptz
	EditedAt    pgtype.Timestamptz
}

func (q *Queries) ListMessages(ctx context.Context) ([]ListMessagesRow, error) {
	rows, err := q.db.Query(ctx, listMessages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMessagesRow
	for rows.Next() {
		var i ListMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.ChatID,
			&i.SenderID,
			&i.Content,
			&i.MessageType,
			&i.ReplyToID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.EditedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMessage = `-- name: UpdateMessage :exec
UPDATE diva_message 
SET content = $1, edited_at = NOW(), updated_at = NOW() 
WHERE id = $2 AND deleted_at IS NULL
`

type UpdateMessageParams struct {
	Content string
	ID      pgtype.UUID
}

func (q *Queries) UpdateMessage(ctx context.Context, arg UpdateMessageParams) error {
	_, err := q.db.Exec(ctx, updateMessage, arg.Content, arg.ID)
	return err
}
