// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: mix.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMix = `-- name: CreateMix :exec
INSERT INTO diva_mix_metadata (collection_id, algorithm_type, time_window_hours, content_weight, freshness_weight, min_engagement_score, excluded_tags, auto_refresh, refresh_interval_seconds)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type CreateMixParams struct {
	CollectionID           pgtype.UUID
	AlgorithmType          string
	TimeWindowHours        int32
	ContentWeight          pgtype.Numeric
	FreshnessWeight        pgtype.Numeric
	MinEngagementScore     int32
	ExcludedTags           []string
	AutoRefresh            bool
	RefreshIntervalSeconds int32
}

func (q *Queries) CreateMix(ctx context.Context, arg CreateMixParams) error {
	_, err := q.db.Exec(ctx, createMix,
		arg.CollectionID,
		arg.AlgorithmType,
		arg.TimeWindowHours,
		arg.ContentWeight,
		arg.FreshnessWeight,
		arg.MinEngagementScore,
		arg.ExcludedTags,
		arg.AutoRefresh,
		arg.RefreshIntervalSeconds,
	)
	return err
}

const deleteMix = `-- name: DeleteMix :exec
DELETE FROM diva_mix_metadata
WHERE collection_id = $1
`

func (q *Queries) DeleteMix(ctx context.Context, collectionID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteMix, collectionID)
	return err
}

const updateMix = `-- name: UpdateMix :exec
UPDATE diva_mix_metadata
SET algorithm_type = $1, time_window_hours = $2, content_weight = $3, freshness_weight = $4, min_engagement_score = $5, excluded_tags = $6, auto_refresh = $7, refresh_interval_seconds = $8
WHERE collection_id = $9
`

type UpdateMixParams struct {
	AlgorithmType          string
	TimeWindowHours        int32
	ContentWeight          pgtype.Numeric
	FreshnessWeight        pgtype.Numeric
	MinEngagementScore     int32
	ExcludedTags           []string
	AutoRefresh            bool
	RefreshIntervalSeconds int32
	CollectionID           pgtype.UUID
}

func (q *Queries) UpdateMix(ctx context.Context, arg UpdateMixParams) error {
	_, err := q.db.Exec(ctx, updateMix,
		arg.AlgorithmType,
		arg.TimeWindowHours,
		arg.ContentWeight,
		arg.FreshnessWeight,
		arg.MinEngagementScore,
		arg.ExcludedTags,
		arg.AutoRefresh,
		arg.RefreshIntervalSeconds,
		arg.CollectionID,
	)
	return err
}
