// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type DivaChat struct {
	ID            pgtype.UUID
	CreatedBy     pgtype.UUID
	ChatType      string
	Name          string
	Description   string
	Avatar        pgtype.UUID
	LastMessageAt pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	DeletedAt     pgtype.Timestamptz
}

type DivaChatParticipant struct {
	ChatID     pgtype.UUID
	UserID     pgtype.UUID
	Role       string
	JoinedAt   pgtype.Timestamptz
	LastReadAt pgtype.Timestamptz
	AddedBy    pgtype.UUID
}

type DivaCollection struct {
	ID             pgtype.UUID
	Owner          pgtype.UUID
	CoverMediaID   pgtype.UUID
	Name           string
	Description    string
	CollectionType string
	Visibility     string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	DeletedAt      pgtype.Timestamptz
}

type DivaCollectionComment struct {
	InteractionID pgtype.UUID
	ReplyTo       pgtype.UUID
	Content       string
	EditedAt      pgtype.Timestamptz
}

type DivaCollectionInteraction struct {
	ID           pgtype.UUID
	CollectionID pgtype.UUID
	UserID       pgtype.UUID
	ReactionType string
	CreatedAt    pgtype.Timestamptz
}

type DivaCollectionMedium struct {
	CollectionID pgtype.UUID
	MediaID      pgtype.UUID
	Position     int32
	AddedBy      pgtype.UUID
	Score        pgtype.Numeric
	AddedAt      pgtype.Timestamptz
}

type DivaCollectionShare struct {
	InteractionID pgtype.UUID
	ShareType     string
	Caption       string
}

type DivaEmailVerificationToken struct {
	UserID    pgtype.UUID
	Token     string
	ExpiresAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type DivaFollow struct {
	UserID     pgtype.UUID
	Followed   pgtype.UUID
	FollowedAt pgtype.Timestamptz
}

type DivaMediaTag struct {
	MediaID pgtype.UUID
	TagID   pgtype.UUID
}

type DivaMedium struct {
	ID               pgtype.UUID
	SubmittedBy      pgtype.UUID
	Url              string
	AltText          string
	MediaType        string
	FileSize         int64
	Width            int32
	Height           int32
	Duration         int32
	Visibility       string
	SensitiveContent bool
	AdultContent     bool
	PublishedAt      pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	DeletedAt        pgtype.Timestamptz
}

type DivaMessage struct {
	ID          pgtype.UUID
	ChatID      pgtype.UUID
	SenderID    pgtype.UUID
	Content     string
	MessageType string
	ReplyToID   pgtype.UUID
	EditedAt    pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	DeletedAt   pgtype.Timestamptz
}

type DivaMessageInteraction struct {
	ID           pgtype.UUID
	MessageID    pgtype.UUID
	UserID       pgtype.UUID
	ReactionType string
	CreatedAt    pgtype.Timestamptz
}

type DivaMessageMedium struct {
	MessageID pgtype.UUID
	MediaID   pgtype.UUID
}

type DivaMixMetadatum struct {
	CollectionID           pgtype.UUID
	AlgorithmType          string
	TimeWindowHours        int32
	ContentWeight          pgtype.Numeric
	FreshnessWeight        pgtype.Numeric
	MinEngagementScore     int32
	ExcludedTags           []string
	AutoRefresh            bool
	RefreshIntervalSeconds int32
}

type DivaPermission struct {
	ID          pgtype.UUID
	Name        string
	Description string
	Resource    string
	Action      string
	RoleLevel   string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	DeletedAt   pgtype.Timestamptz
}

type DivaPlaylistContributor struct {
	CollectionID  pgtype.UUID
	ContributorID pgtype.UUID
}

type DivaPlaylistMetadatum struct {
	CollectionID     pgtype.UUID
	IsCollaborative  bool
	AllowSuggestions bool
}

type DivaPlaylistSuggestion struct {
	CollectionID pgtype.UUID
	SuggesterID  pgtype.UUID
	MediaID      pgtype.UUID
	Status       string
	SuggestedAt  pgtype.Timestamptz
}

type DivaPost struct {
	ID         pgtype.UUID
	AuthorID   pgtype.UUID
	Text       string
	Visibility string
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
	DeletedAt  pgtype.Timestamptz
}

type DivaPostAttachment struct {
	ID           pgtype.UUID
	PostID       pgtype.UUID
	MediaID      pgtype.UUID
	CollectionID pgtype.UUID
}

type DivaPostComment struct {
	InteractionID pgtype.UUID
	ReplyTo       pgtype.UUID
	Content       string
	EditedAt      pgtype.Timestamptz
}

type DivaPostInteraction struct {
	ID           pgtype.UUID
	PostID       pgtype.UUID
	UserID       pgtype.UUID
	ReactionType string
	CreatedAt    pgtype.Timestamptz
}

type DivaPostShare struct {
	InteractionID pgtype.UUID
	ShareType     string
	Caption       string
}

type DivaSession struct {
	ID           pgtype.UUID
	UserID       pgtype.UUID
	AccessToken  string
	RefreshToken string
	Device       string
	Status       string
	IpAddress    string
	UserAgent    string
	ExpiresAt    pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type DivaTag struct {
	ID        pgtype.UUID
	TagName   string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}

type DivaUser struct {
	ID           pgtype.UUID
	Email        string
	Username     string
	PasswordHash string
	BirthDate    pgtype.Timestamptz
	PhoneNumber  string
	Alias        string
	Avatar       string
	Bio          string
	UserVerified bool
	Role         string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	DeletedAt    pgtype.Timestamptz
}

type DivaUserPermission struct {
	PermissionID pgtype.UUID
	UserID       pgtype.UUID
	GrantedBy    pgtype.UUID
	Granted      bool
	GrantedAt    pgtype.Timestamptz
	ExpiresAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type DivaUserPreference struct {
	ID                  pgtype.UUID
	UserID              pgtype.UUID
	Theme               string
	OnboardingCompleted bool
	Language            string
	LastSyncAt          pgtype.Timestamptz
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
}
