// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type ChatTypeType string

const (
	ChatTypeTypeDIRECT      ChatTypeType = "DIRECT"
	ChatTypeTypeGROUP       ChatTypeType = "GROUP"
	ChatTypeTypeUNSPECIFIED ChatTypeType = "UNSPECIFIED"
)

func (e *ChatTypeType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ChatTypeType(s)
	case string:
		*e = ChatTypeType(s)
	default:
		return fmt.Errorf("unsupported scan type for ChatTypeType: %T", src)
	}
	return nil
}

type NullChatTypeType struct {
	ChatTypeType ChatTypeType
	Valid        bool // Valid is true if ChatTypeType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullChatTypeType) Scan(value interface{}) error {
	if value == nil {
		ns.ChatTypeType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ChatTypeType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullChatTypeType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ChatTypeType), nil
}

type CollectionTypeType string

const (
	CollectionTypeTypeALBUM       CollectionTypeType = "ALBUM"
	CollectionTypeTypePLAYLIST    CollectionTypeType = "PLAYLIST"
	CollectionTypeTypeMIX         CollectionTypeType = "MIX"
	CollectionTypeTypeFAVORITES   CollectionTypeType = "FAVORITES"
	CollectionTypeTypeFEATURED    CollectionTypeType = "FEATURED"
	CollectionTypeTypeTRENDING    CollectionTypeType = "TRENDING"
	CollectionTypeTypeUNSPECIFIED CollectionTypeType = "UNSPECIFIED"
)

func (e *CollectionTypeType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CollectionTypeType(s)
	case string:
		*e = CollectionTypeType(s)
	default:
		return fmt.Errorf("unsupported scan type for CollectionTypeType: %T", src)
	}
	return nil
}

type NullCollectionTypeType struct {
	CollectionTypeType CollectionTypeType
	Valid              bool // Valid is true if CollectionTypeType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCollectionTypeType) Scan(value interface{}) error {
	if value == nil {
		ns.CollectionTypeType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CollectionTypeType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCollectionTypeType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CollectionTypeType), nil
}

type MediaTypeType string

const (
	MediaTypeTypeAUDIO       MediaTypeType = "AUDIO"
	MediaTypeTypeIMAGE       MediaTypeType = "IMAGE"
	MediaTypeTypeVIDEO       MediaTypeType = "VIDEO"
	MediaTypeTypeUNSPECIFIED MediaTypeType = "UNSPECIFIED"
)

func (e *MediaTypeType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MediaTypeType(s)
	case string:
		*e = MediaTypeType(s)
	default:
		return fmt.Errorf("unsupported scan type for MediaTypeType: %T", src)
	}
	return nil
}

type NullMediaTypeType struct {
	MediaTypeType MediaTypeType
	Valid         bool // Valid is true if MediaTypeType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMediaTypeType) Scan(value interface{}) error {
	if value == nil {
		ns.MediaTypeType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MediaTypeType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMediaTypeType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MediaTypeType), nil
}

type MessageTypeType string

const (
	MessageTypeTypeTEXT        MessageTypeType = "TEXT"
	MessageTypeTypeMEDIA       MessageTypeType = "MEDIA"
	MessageTypeTypeSYSTEM      MessageTypeType = "SYSTEM"
	MessageTypeTypeUNSPECIFIED MessageTypeType = "UNSPECIFIED"
)

func (e *MessageTypeType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MessageTypeType(s)
	case string:
		*e = MessageTypeType(s)
	default:
		return fmt.Errorf("unsupported scan type for MessageTypeType: %T", src)
	}
	return nil
}

type NullMessageTypeType struct {
	MessageTypeType MessageTypeType
	Valid           bool // Valid is true if MessageTypeType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMessageTypeType) Scan(value interface{}) error {
	if value == nil {
		ns.MessageTypeType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MessageTypeType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMessageTypeType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MessageTypeType), nil
}

type ModerationStatusType string

const (
	ModerationStatusTypePENDING     ModerationStatusType = "PENDING"
	ModerationStatusTypeAPPROVED    ModerationStatusType = "APPROVED"
	ModerationStatusTypeREJECTED    ModerationStatusType = "REJECTED"
	ModerationStatusTypeHIDDEN      ModerationStatusType = "HIDDEN"
	ModerationStatusTypeUNSPECIFIED ModerationStatusType = "UNSPECIFIED"
)

func (e *ModerationStatusType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ModerationStatusType(s)
	case string:
		*e = ModerationStatusType(s)
	default:
		return fmt.Errorf("unsupported scan type for ModerationStatusType: %T", src)
	}
	return nil
}

type NullModerationStatusType struct {
	ModerationStatusType ModerationStatusType
	Valid                bool // Valid is true if ModerationStatusType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullModerationStatusType) Scan(value interface{}) error {
	if value == nil {
		ns.ModerationStatusType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ModerationStatusType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullModerationStatusType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ModerationStatusType), nil
}

type ParticipantRoleType string

const (
	ParticipantRoleTypeOWNER       ParticipantRoleType = "OWNER"
	ParticipantRoleTypeADMIN       ParticipantRoleType = "ADMIN"
	ParticipantRoleTypeMEMBER      ParticipantRoleType = "MEMBER"
	ParticipantRoleTypeUNSPECIFIED ParticipantRoleType = "UNSPECIFIED"
)

func (e *ParticipantRoleType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ParticipantRoleType(s)
	case string:
		*e = ParticipantRoleType(s)
	default:
		return fmt.Errorf("unsupported scan type for ParticipantRoleType: %T", src)
	}
	return nil
}

type NullParticipantRoleType struct {
	ParticipantRoleType ParticipantRoleType
	Valid               bool // Valid is true if ParticipantRoleType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullParticipantRoleType) Scan(value interface{}) error {
	if value == nil {
		ns.ParticipantRoleType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ParticipantRoleType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullParticipantRoleType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ParticipantRoleType), nil
}

type ReactionTypeType string

const (
	ReactionTypeTypeLIKE        ReactionTypeType = "LIKE"
	ReactionTypeTypeCOMMENT     ReactionTypeType = "COMMENT"
	ReactionTypeTypeBOOKMARK    ReactionTypeType = "BOOKMARK"
	ReactionTypeTypeSHARE       ReactionTypeType = "SHARE"
	ReactionTypeTypeUNSPECIFIED ReactionTypeType = "UNSPECIFIED"
)

func (e *ReactionTypeType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ReactionTypeType(s)
	case string:
		*e = ReactionTypeType(s)
	default:
		return fmt.Errorf("unsupported scan type for ReactionTypeType: %T", src)
	}
	return nil
}

type NullReactionTypeType struct {
	ReactionTypeType ReactionTypeType
	Valid            bool // Valid is true if ReactionTypeType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullReactionTypeType) Scan(value interface{}) error {
	if value == nil {
		ns.ReactionTypeType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ReactionTypeType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullReactionTypeType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ReactionTypeType), nil
}

type RoleType string

const (
	RoleTypeUSER      RoleType = "USER"
	RoleTypeMODERATOR RoleType = "MODERATOR"
	RoleTypeADMIN     RoleType = "ADMIN"
)

func (e *RoleType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RoleType(s)
	case string:
		*e = RoleType(s)
	default:
		return fmt.Errorf("unsupported scan type for RoleType: %T", src)
	}
	return nil
}

type NullRoleType struct {
	RoleType RoleType
	Valid    bool // Valid is true if RoleType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRoleType) Scan(value interface{}) error {
	if value == nil {
		ns.RoleType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RoleType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRoleType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RoleType), nil
}

type SessionStatusType string

const (
	SessionStatusTypeACTIVE  SessionStatusType = "ACTIVE"
	SessionStatusTypeEXPIRED SessionStatusType = "EXPIRED"
	SessionStatusTypeCLOSED  SessionStatusType = "CLOSED"
)

func (e *SessionStatusType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SessionStatusType(s)
	case string:
		*e = SessionStatusType(s)
	default:
		return fmt.Errorf("unsupported scan type for SessionStatusType: %T", src)
	}
	return nil
}

type NullSessionStatusType struct {
	SessionStatusType SessionStatusType
	Valid             bool // Valid is true if SessionStatusType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSessionStatusType) Scan(value interface{}) error {
	if value == nil {
		ns.SessionStatusType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SessionStatusType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSessionStatusType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SessionStatusType), nil
}

type ShareTypeType string

const (
	ShareTypeTypeDIRECT      ShareTypeType = "DIRECT"
	ShareTypeTypeEXTERNAL    ShareTypeType = "EXTERNAL"
	ShareTypeTypeEMBED       ShareTypeType = "EMBED"
	ShareTypeTypeDOWNLOAD    ShareTypeType = "DOWNLOAD"
	ShareTypeTypeUNSPECIFIED ShareTypeType = "UNSPECIFIED"
)

func (e *ShareTypeType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ShareTypeType(s)
	case string:
		*e = ShareTypeType(s)
	default:
		return fmt.Errorf("unsupported scan type for ShareTypeType: %T", src)
	}
	return nil
}

type NullShareTypeType struct {
	ShareTypeType ShareTypeType
	Valid         bool // Valid is true if ShareTypeType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullShareTypeType) Scan(value interface{}) error {
	if value == nil {
		ns.ShareTypeType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ShareTypeType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullShareTypeType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ShareTypeType), nil
}

type ThemeType string

const (
	ThemeTypeLIGHT  ThemeType = "LIGHT"
	ThemeTypeDARK   ThemeType = "DARK"
	ThemeTypeSYSTEM ThemeType = "SYSTEM"
)

func (e *ThemeType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ThemeType(s)
	case string:
		*e = ThemeType(s)
	default:
		return fmt.Errorf("unsupported scan type for ThemeType: %T", src)
	}
	return nil
}

type NullThemeType struct {
	ThemeType ThemeType
	Valid     bool // Valid is true if ThemeType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullThemeType) Scan(value interface{}) error {
	if value == nil {
		ns.ThemeType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ThemeType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullThemeType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ThemeType), nil
}

type VisibilityType string

const (
	VisibilityTypePUBLIC      VisibilityType = "PUBLIC"
	VisibilityTypePRIVATE     VisibilityType = "PRIVATE"
	VisibilityTypeFRIENDS     VisibilityType = "FRIENDS"
	VisibilityTypeUNSPECIFIED VisibilityType = "UNSPECIFIED"
)

func (e *VisibilityType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = VisibilityType(s)
	case string:
		*e = VisibilityType(s)
	default:
		return fmt.Errorf("unsupported scan type for VisibilityType: %T", src)
	}
	return nil
}

type NullVisibilityType struct {
	VisibilityType VisibilityType
	Valid          bool // Valid is true if VisibilityType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullVisibilityType) Scan(value interface{}) error {
	if value == nil {
		ns.VisibilityType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.VisibilityType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullVisibilityType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.VisibilityType), nil
}

type DivaChat struct {
	ID            pgtype.UUID
	CreatedBy     pgtype.UUID
	ChatType      ChatTypeType
	Name          string
	Description   string
	Avatar        pgtype.UUID
	LastMessageAt pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	DeletedAt     pgtype.Timestamptz
}

type DivaChatParticipant struct {
	ChatID     pgtype.UUID
	UserID     pgtype.UUID
	Role       ParticipantRoleType
	JoinedAt   pgtype.Timestamptz
	LastReadAt pgtype.Timestamptz
	AddedBy    pgtype.UUID
}

type DivaCollection struct {
	ID             pgtype.UUID
	Owner          pgtype.UUID
	CoverMediaID   pgtype.UUID
	Name           string
	Description    string
	CollectionType CollectionTypeType
	Visibility     VisibilityType
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	DeletedAt      pgtype.Timestamptz
}

type DivaCollectionComment struct {
	InteractionID pgtype.UUID
	ReplyTo       pgtype.UUID
	Content       string
	EditedAt      pgtype.Timestamptz
}

type DivaCollectionInteraction struct {
	ID           pgtype.UUID
	CollectionID pgtype.UUID
	UserID       pgtype.UUID
	ReactionType ReactionTypeType
	CreatedAt    pgtype.Timestamptz
}

type DivaCollectionMedium struct {
	CollectionID pgtype.UUID
	MediaID      pgtype.UUID
	Position     int32
	AddedBy      pgtype.UUID
	Score        pgtype.Numeric
	AddedAt      pgtype.Timestamptz
}

type DivaCollectionShare struct {
	InteractionID pgtype.UUID
	ShareType     ShareTypeType
	Caption       string
}

type DivaEmailVerificationToken struct {
	UserID    pgtype.UUID
	Token     string
	ExpiresAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type DivaFollow struct {
	UserID     pgtype.UUID
	Followed   pgtype.UUID
	FollowedAt pgtype.Timestamptz
}

type DivaMediaTag struct {
	MediaID pgtype.UUID
	TagID   pgtype.UUID
}

type DivaMedium struct {
	ID               pgtype.UUID
	SubmittedBy      pgtype.UUID
	Url              string
	AltText          string
	MediaType        MediaTypeType
	FileSize         int64
	Width            int32
	Height           int32
	Duration         int32
	Visibility       VisibilityType
	SensitiveContent bool
	AdultContent     bool
	PublishedAt      pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	DeletedAt        pgtype.Timestamptz
}

type DivaMessage struct {
	ID          pgtype.UUID
	ChatID      pgtype.UUID
	SenderID    pgtype.UUID
	Content     string
	MessageType MessageTypeType
	ReplyToID   pgtype.UUID
	EditedAt    pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	DeletedAt   pgtype.Timestamptz
}

type DivaMessageInteraction struct {
	ID           pgtype.UUID
	MessageID    pgtype.UUID
	UserID       pgtype.UUID
	ReactionType ReactionTypeType
	CreatedAt    pgtype.Timestamptz
}

type DivaMessageMedium struct {
	MessageID pgtype.UUID
	MediaID   pgtype.UUID
}

type DivaMixMetadatum struct {
	CollectionID           pgtype.UUID
	AlgorithmType          string
	TimeWindowHours        int32
	ContentWeight          pgtype.Numeric
	FreshnessWeight        pgtype.Numeric
	MinEngagementScore     int32
	ExcludedTags           []string
	AutoRefresh            bool
	RefreshIntervalSeconds int32
}

type DivaPermission struct {
	ID          pgtype.UUID
	Name        string
	Description string
	Resource    string
	Action      string
	RoleLevel   RoleType
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	DeletedAt   pgtype.Timestamptz
}

type DivaPlaylistContributor struct {
	CollectionID  pgtype.UUID
	ContributorID pgtype.UUID
}

type DivaPlaylistMetadatum struct {
	CollectionID     pgtype.UUID
	IsCollaborative  bool
	AllowSuggestions bool
}

type DivaPlaylistSuggestion struct {
	CollectionID pgtype.UUID
	SuggesterID  pgtype.UUID
	MediaID      pgtype.UUID
	Status       ModerationStatusType
	SuggestedAt  pgtype.Timestamptz
}

type DivaPost struct {
	ID         pgtype.UUID
	AuthorID   pgtype.UUID
	Text       string
	Visibility string
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
	DeletedAt  pgtype.Timestamptz
}

type DivaPostAttachment struct {
	ID           pgtype.UUID
	PostID       pgtype.UUID
	MediaID      pgtype.UUID
	CollectionID pgtype.UUID
}

type DivaPostComment struct {
	InteractionID pgtype.UUID
	ReplyTo       pgtype.UUID
	Content       string
	EditedAt      pgtype.Timestamptz
}

type DivaPostInteraction struct {
	ID           pgtype.UUID
	PostID       pgtype.UUID
	UserID       pgtype.UUID
	ReactionType ReactionTypeType
	CreatedAt    pgtype.Timestamptz
}

type DivaPostShare struct {
	InteractionID pgtype.UUID
	ShareType     ShareTypeType
	Caption       string
}

type DivaSession struct {
	ID           pgtype.UUID
	UserID       pgtype.UUID
	AccessToken  string
	RefreshToken string
	Device       string
	Status       SessionStatusType
	IpAddress    string
	UserAgent    string
	ExpiresAt    pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type DivaTag struct {
	ID        pgtype.UUID
	TagName   string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}

type DivaUser struct {
	ID           pgtype.UUID
	Email        string
	Username     string
	PasswordHash string
	BirthDate    pgtype.Timestamptz
	PhoneNumber  string
	Alias        string
	Avatar       string
	Bio          string
	UserVerified bool
	Role         RoleType
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	DeletedAt    pgtype.Timestamptz
}

type DivaUserPendingAction struct {
	UserID     pgtype.UUID
	ActionName string
}

type DivaUserPermission struct {
	PermissionID pgtype.UUID
	UserID       pgtype.UUID
	GrantedBy    pgtype.UUID
	Granted      bool
	GrantedAt    pgtype.Timestamptz
	ExpiresAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type DivaUserPreference struct {
	ID                  pgtype.UUID
	UserID              pgtype.UUID
	Theme               ThemeType
	OnboardingCompleted bool
	Language            string
	LastSyncAt          pgtype.Timestamptz
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
}
