// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: permissions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPermission = `-- name: CreatePermission :exec
insert into diva_permissions (
    id,
    name,
    description,
    action,
    role_level,
    created_at,
    updated_at
) values (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
`

type CreatePermissionParams struct {
	ID          pgtype.UUID
	Name        string
	Description string
	Action      string
	RoleLevel   RoleType
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) CreatePermission(ctx context.Context, arg CreatePermissionParams) error {
	_, err := q.db.Exec(ctx, createPermission,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Action,
		arg.RoleLevel,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deletePermission = `-- name: DeletePermission :exec
delete from diva_permissions
where id = $1
`

func (q *Queries) DeletePermission(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deletePermission, id)
	return err
}

const getPermissionByID = `-- name: GetPermissionByID :one
select
    p.id as id,
    p.name,
    p.description,
    p.action,
    p.role_level as roleLevel,
    p.created_at as createdAt,
    p.updated_at as updatedAt,
    p.deleted_at as deletedAt
from diva_permissions p
where p.id = $1
`

type GetPermissionByIDRow struct {
	ID          pgtype.UUID
	Name        string
	Description string
	Action      string
	Rolelevel   RoleType
	Createdat   pgtype.Timestamptz
	Updatedat   pgtype.Timestamptz
	Deletedat   pgtype.Timestamptz
}

func (q *Queries) GetPermissionByID(ctx context.Context, id pgtype.UUID) (GetPermissionByIDRow, error) {
	row := q.db.QueryRow(ctx, getPermissionByID, id)
	var i GetPermissionByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Action,
		&i.Rolelevel,
		&i.Createdat,
		&i.Updatedat,
		&i.Deletedat,
	)
	return i, err
}

const getPermissionByName = `-- name: GetPermissionByName :one
select
    p.id as id,
    p.name,
    p.description,
    p.action,
    p.role_level as roleLevel,
    p.created_at as createdAt,
    p.updated_at as updatedAt,
    p.deleted_at as deletedAt
from diva_permissions p
where p.name = $1
`

type GetPermissionByNameRow struct {
	ID          pgtype.UUID
	Name        string
	Description string
	Action      string
	Rolelevel   RoleType
	Createdat   pgtype.Timestamptz
	Updatedat   pgtype.Timestamptz
	Deletedat   pgtype.Timestamptz
}

func (q *Queries) GetPermissionByName(ctx context.Context, name string) (GetPermissionByNameRow, error) {
	row := q.db.QueryRow(ctx, getPermissionByName, name)
	var i GetPermissionByNameRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Action,
		&i.Rolelevel,
		&i.Createdat,
		&i.Updatedat,
		&i.Deletedat,
	)
	return i, err
}

const listPermissions = `-- name: ListPermissions :many
select
    p.id as id,
    p.name,
    p.description,
    p.action,
    p.role_level as roleLevel,
    p.created_at as createdAt,
    p.updated_at as updatedAt,
    p.deleted_at as deletedAt
from diva_permissions p
order by p.name
`

type ListPermissionsRow struct {
	ID          pgtype.UUID
	Name        string
	Description string
	Action      string
	Rolelevel   RoleType
	Createdat   pgtype.Timestamptz
	Updatedat   pgtype.Timestamptz
	Deletedat   pgtype.Timestamptz
}

func (q *Queries) ListPermissions(ctx context.Context) ([]ListPermissionsRow, error) {
	rows, err := q.db.Query(ctx, listPermissions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPermissionsRow
	for rows.Next() {
		var i ListPermissionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Action,
			&i.Rolelevel,
			&i.Createdat,
			&i.Updatedat,
			&i.Deletedat,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restorePermission = `-- name: RestorePermission :exec
update diva_permissions
set
    deleted_at = null
where id = $1
`

func (q *Queries) RestorePermission(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, restorePermission, id)
	return err
}

const softDeletePermission = `-- name: SoftDeletePermission :exec
update diva_permissions
set
    deleted_at = now()
where id = $1
`

func (q *Queries) SoftDeletePermission(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, softDeletePermission, id)
	return err
}

const updatePermission = `-- name: UpdatePermission :exec
update diva_permissions
set
    name = $1,
    description = $2,
    action = $3,
    role_level = $4,
    updated_at = now()
where id = $5
`

type UpdatePermissionParams struct {
	Name        string
	Description string
	Action      string
	RoleLevel   RoleType
	ID          pgtype.UUID
}

func (q *Queries) UpdatePermission(ctx context.Context, arg UpdatePermissionParams) error {
	_, err := q.db.Exec(ctx, updatePermission,
		arg.Name,
		arg.Description,
		arg.Action,
		arg.RoleLevel,
		arg.ID,
	)
	return err
}
