// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: permissions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPermissions = `-- name: CountPermissions :one
select count(*) from diva_permissions
`

func (q *Queries) CountPermissions(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPermissions)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPermission = `-- name: CreatePermission :exec
insert into diva_permissions (
    id,
    name,
    description,
    action,
    role_level
) values (
    $1,
    $2,
    $3,
    $4,
    $5
)
`

type CreatePermissionParams struct {
	ID          pgtype.UUID
	Name        string
	Description string
	Action      string
	RoleLevel   RoleType
}

func (q *Queries) CreatePermission(ctx context.Context, arg CreatePermissionParams) error {
	_, err := q.db.Exec(ctx, createPermission,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Action,
		arg.RoleLevel,
	)
	return err
}

const deletePermission = `-- name: DeletePermission :exec
delete from diva_permissions
where id = $1
`

func (q *Queries) DeletePermission(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deletePermission, id)
	return err
}

const getPermissionByID = `-- name: GetPermissionByID :one
select
    p.id as id,
    p.name,
    p.description,
    p.action,
    p.role_level,
    p.created_at,
    p.updated_at,
    p.deleted_at
from diva_permissions p
where p.id = $1
`

func (q *Queries) GetPermissionByID(ctx context.Context, id pgtype.UUID) (DivaPermission, error) {
	row := q.db.QueryRow(ctx, getPermissionByID, id)
	var i DivaPermission
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Action,
		&i.RoleLevel,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getPermissionByName = `-- name: GetPermissionByName :one
select
    p.id as id,
    p.name,
    p.description,
    p.action,
    p.role_level,
    p.created_at,
    p.updated_at,
    p.deleted_at
from diva_permissions p
where p.name = $1
`

func (q *Queries) GetPermissionByName(ctx context.Context, name string) (DivaPermission, error) {
	row := q.db.QueryRow(ctx, getPermissionByName, name)
	var i DivaPermission
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Action,
		&i.RoleLevel,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listPermissions = `-- name: ListPermissions :many
select
    p.id as id,
    p.name,
    p.description,
    p.action,
    p.role_level,
    p.created_at,
    p.updated_at,
    p.deleted_at
from diva_permissions p
order by p.name
limit $1
offset $2
`

type ListPermissionsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListPermissions(ctx context.Context, arg ListPermissionsParams) ([]DivaPermission, error) {
	rows, err := q.db.Query(ctx, listPermissions, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DivaPermission
	for rows.Next() {
		var i DivaPermission
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Action,
			&i.RoleLevel,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restorePermission = `-- name: RestorePermission :exec
update diva_permissions set
    deleted_at = null
where id = $1
`

func (q *Queries) RestorePermission(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, restorePermission, id)
	return err
}

const softDeletePermission = `-- name: SoftDeletePermission :exec
update diva_permissions
set
    deleted_at = now()
where id = $1
`

func (q *Queries) SoftDeletePermission(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, softDeletePermission, id)
	return err
}

const updatePermission = `-- name: UpdatePermission :exec
update diva_permissions set
    name = $1,
    description = $2,
    action = $3,
    role_level = $4,
    updated_at = now()
where id = $5
`

type UpdatePermissionParams struct {
	Name        string
	Description string
	Action      string
	RoleLevel   RoleType
	ID          pgtype.UUID
}

func (q *Queries) UpdatePermission(ctx context.Context, arg UpdatePermissionParams) error {
	_, err := q.db.Exec(ctx, updatePermission,
		arg.Name,
		arg.Description,
		arg.Action,
		arg.RoleLevel,
		arg.ID,
	)
	return err
}
