// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: permissions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPermissions = `-- name: CountPermissions :one
SELECT COUNT(*)
FROM diva_permissions
WHERE deleted_at IS NULL
`

func (q *Queries) CountPermissions(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPermissions)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPermission = `-- name: CreatePermission :exec
INSERT INTO diva_permissions (id, name, description, role_level)
VALUES ($1, $2, $3, $4)
`

type CreatePermissionParams struct {
	ID          pgtype.UUID
	Name        string
	Description string
	RoleLevel   RoleType
}

func (q *Queries) CreatePermission(ctx context.Context, arg CreatePermissionParams) error {
	_, err := q.db.Exec(ctx, createPermission,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.RoleLevel,
	)
	return err
}

const deletePermission = `-- name: DeletePermission :exec
UPDATE diva_permissions
SET deleted_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) DeletePermission(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deletePermission, id)
	return err
}

const getPermissionByID = `-- name: GetPermissionByID :one
SELECT
  id,
  name,
  description,
  role_level,
  created_at,
  updated_at,
  deleted_at
FROM diva_permissions
WHERE id = $1
`

type GetPermissionByIDRow struct {
	ID          pgtype.UUID
	Name        string
	Description string
	RoleLevel   RoleType
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	DeletedAt   pgtype.Timestamptz
}

func (q *Queries) GetPermissionByID(ctx context.Context, id pgtype.UUID) (GetPermissionByIDRow, error) {
	row := q.db.QueryRow(ctx, getPermissionByID, id)
	var i GetPermissionByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.RoleLevel,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listPermissions = `-- name: ListPermissions :many
SELECT
  id,
  name,
  description,
  role_level,
  created_at,
  updated_at,
  deleted_at
FROM diva_permissions
WHERE deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListPermissionsParams struct {
	Limit  int32
	Offset int32
}

type ListPermissionsRow struct {
	ID          pgtype.UUID
	Name        string
	Description string
	RoleLevel   RoleType
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	DeletedAt   pgtype.Timestamptz
}

func (q *Queries) ListPermissions(ctx context.Context, arg ListPermissionsParams) ([]ListPermissionsRow, error) {
	rows, err := q.db.Query(ctx, listPermissions, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPermissionsRow
	for rows.Next() {
		var i ListPermissionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.RoleLevel,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePermission = `-- name: UpdatePermission :exec
UPDATE diva_permissions
SET name = $1, description = $2, updated_at = NOW()
WHERE id = $3 AND deleted_at IS NULL
`

type UpdatePermissionParams struct {
	Name        string
	Description string
	ID          pgtype.UUID
}

func (q *Queries) UpdatePermission(ctx context.Context, arg UpdatePermissionParams) error {
	_, err := q.db.Exec(ctx, updatePermission, arg.Name, arg.Description, arg.ID)
	return err
}
