// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: playlist_suggestion.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPlaylistSuggestion = `-- name: CreatePlaylistSuggestion :exec
INSERT INTO diva_playlist_suggestions (collection_id, suggester_id, media_id, status)
VALUES ($1, $2, $3, $4)
`

type CreatePlaylistSuggestionParams struct {
	CollectionID pgtype.UUID
	SuggesterID  pgtype.UUID
	MediaID      pgtype.UUID
	Status       string
}

func (q *Queries) CreatePlaylistSuggestion(ctx context.Context, arg CreatePlaylistSuggestionParams) error {
	_, err := q.db.Exec(ctx, createPlaylistSuggestion,
		arg.CollectionID,
		arg.SuggesterID,
		arg.MediaID,
		arg.Status,
	)
	return err
}

const updatePlaylistSuggestion = `-- name: UpdatePlaylistSuggestion :exec
UPDATE diva_playlist_suggestions
SET status = $1
WHERE collection_id = $2 AND suggester_id = $3 AND media_id = $4
`

type UpdatePlaylistSuggestionParams struct {
	Status       string
	CollectionID pgtype.UUID
	SuggesterID  pgtype.UUID
	MediaID      pgtype.UUID
}

func (q *Queries) UpdatePlaylistSuggestion(ctx context.Context, arg UpdatePlaylistSuggestionParams) error {
	_, err := q.db.Exec(ctx, updatePlaylistSuggestion,
		arg.Status,
		arg.CollectionID,
		arg.SuggesterID,
		arg.MediaID,
	)
	return err
}
