// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: playlist_contributor.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPlaylistContributor = `-- name: CreatePlaylistContributor :exec
INSERT INTO diva_playlist_contributor (collection_id, contributor_id)
VALUES ($1, $2)
`

type CreatePlaylistContributorParams struct {
	CollectionID  pgtype.UUID
	ContributorID pgtype.UUID
}

func (q *Queries) CreatePlaylistContributor(ctx context.Context, arg CreatePlaylistContributorParams) error {
	_, err := q.db.Exec(ctx, createPlaylistContributor, arg.CollectionID, arg.ContributorID)
	return err
}

const deletePlaylistContributor = `-- name: DeletePlaylistContributor :exec
DELETE FROM diva_playlist_contributor
WHERE collection_id = $1 AND contributor_id = $2
`

type DeletePlaylistContributorParams struct {
	CollectionID  pgtype.UUID
	ContributorID pgtype.UUID
}

func (q *Queries) DeletePlaylistContributor(ctx context.Context, arg DeletePlaylistContributorParams) error {
	_, err := q.db.Exec(ctx, deletePlaylistContributor, arg.CollectionID, arg.ContributorID)
	return err
}

const updatePlaylistContributor = `-- name: UpdatePlaylistContributor :exec
UPDATE diva_playlist_contributor
SET collection_id = $1, contributor_id = $2
WHERE collection_id = $3 AND contributor_id = $4
`

type UpdatePlaylistContributorParams struct {
	CollectionID    pgtype.UUID
	ContributorID   pgtype.UUID
	CollectionID_2  pgtype.UUID
	ContributorID_2 pgtype.UUID
}

func (q *Queries) UpdatePlaylistContributor(ctx context.Context, arg UpdatePlaylistContributorParams) error {
	_, err := q.db.Exec(ctx, updatePlaylistContributor,
		arg.CollectionID,
		arg.ContributorID,
		arg.CollectionID_2,
		arg.ContributorID_2,
	)
	return err
}
