// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: post.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPost = `-- name: CountPost :one
SELECT COUNT(*)
FROM diva_post
WHERE deleted_at IS NULL
`

func (q *Queries) CountPost(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPost)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPost = `-- name: CreatePost :exec
INSERT INTO diva_post (id, author_id, text, visibility)
VALUES ($1, $2, $3, $4)
`

type CreatePostParams struct {
	ID         pgtype.UUID
	AuthorID   pgtype.UUID
	Text       string
	Visibility string
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) error {
	_, err := q.db.Exec(ctx, createPost,
		arg.ID,
		arg.AuthorID,
		arg.Text,
		arg.Visibility,
	)
	return err
}

const deletePost = `-- name: DeletePost :exec
UPDATE diva_post 
SET deleted_at = NOW() 
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) DeletePost(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deletePost, id)
	return err
}

const getPostByID = `-- name: GetPostByID :one
SELECT 
  id,
  author_id,
  text,
  visibility,
  created_at,
  updated_at,
  deleted_at
FROM diva_post
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetPostByID(ctx context.Context, id pgtype.UUID) (DivaPost, error) {
	row := q.db.QueryRow(ctx, getPostByID, id)
	var i DivaPost
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.Text,
		&i.Visibility,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listPosts = `-- name: ListPosts :many
SELECT 
  id,
  author_id,
  text,
  visibility,
  created_at,
  updated_at,
  deleted_at
FROM diva_post
WHERE deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListPostsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListPosts(ctx context.Context, arg ListPostsParams) ([]DivaPost, error) {
	rows, err := q.db.Query(ctx, listPosts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DivaPost
	for rows.Next() {
		var i DivaPost
		if err := rows.Scan(
			&i.ID,
			&i.AuthorID,
			&i.Text,
			&i.Visibility,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
