// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: session.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :exec
INSERT INTO diva_session (id, user_id, access_token, refresh_token, device, status, ip_address, user_agent, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type CreateSessionParams struct {
	ID           pgtype.UUID
	UserID       pgtype.UUID
	AccessToken  string
	RefreshToken string
	Device       string
	Status       SessionStatusType
	IpAddress    string
	UserAgent    string
	ExpiresAt    pgtype.Timestamptz
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.AccessToken,
		arg.RefreshToken,
		arg.Device,
		arg.Status,
		arg.IpAddress,
		arg.UserAgent,
		arg.ExpiresAt,
	)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
delete from diva_session
where id = $1
`

func (q *Queries) DeleteSession(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSession, id)
	return err
}

const deleteSessionByUserID = `-- name: DeleteSessionByUserID :exec
delete from diva_session
where user_id = $1
`

func (q *Queries) DeleteSessionByUserID(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSessionByUserID, userID)
	return err
}

const getSessionByID = `-- name: GetSessionByID :one
select
    s.id,
    s.access_token,
    s.refresh_token,
    s.device,
    s.status,
    s.ip_address,
    s.user_agent,
    s.expires_at,
    s.created_at,
    s.updated_at,
    u.id as user_id,
    u.email,
    u.username,
    u.user_verified,
    u.role,
    u.created_at,
    u.updated_at
from diva_session s
left join diva_user u on s.user_id = u.id
where s.id = $1 and u.deleted_at is null
`

type GetSessionByIDRow struct {
	ID           pgtype.UUID
	AccessToken  string
	RefreshToken string
	Device       string
	Status       SessionStatusType
	IpAddress    string
	UserAgent    string
	ExpiresAt    pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	UserID       pgtype.UUID
	Email        pgtype.Text
	Username     pgtype.Text
	UserVerified pgtype.Bool
	Role         NullRoleType
	CreatedAt_2  pgtype.Timestamptz
	UpdatedAt_2  pgtype.Timestamptz
}

func (q *Queries) GetSessionByID(ctx context.Context, id pgtype.UUID) (GetSessionByIDRow, error) {
	row := q.db.QueryRow(ctx, getSessionByID, id)
	var i GetSessionByIDRow
	err := row.Scan(
		&i.ID,
		&i.AccessToken,
		&i.RefreshToken,
		&i.Device,
		&i.Status,
		&i.IpAddress,
		&i.UserAgent,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.Email,
		&i.Username,
		&i.UserVerified,
		&i.Role,
		&i.CreatedAt_2,
		&i.UpdatedAt_2,
	)
	return i, err
}

const getSessionsByUser = `-- name: GetSessionsByUser :many
select
    s.id,
    s.access_token,
    s.refresh_token,
    s.device,
    s.status,
    s.ip_address,
    s.user_agent,
    s.expires_at,
    s.created_at,
    s.updated_at,
    u.id as user_id,
    u.email,
    u.username,
    u.user_verified,
    u.role,
    u.created_at,
    u.updated_at
from diva_session s
left join diva_user u on s.user_id = u.id
where u.id = $1 and u.deleted_at is null
`

type GetSessionsByUserRow struct {
	ID           pgtype.UUID
	AccessToken  string
	RefreshToken string
	Device       string
	Status       SessionStatusType
	IpAddress    string
	UserAgent    string
	ExpiresAt    pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	UserID       pgtype.UUID
	Email        pgtype.Text
	Username     pgtype.Text
	UserVerified pgtype.Bool
	Role         NullRoleType
	CreatedAt_2  pgtype.Timestamptz
	UpdatedAt_2  pgtype.Timestamptz
}

func (q *Queries) GetSessionsByUser(ctx context.Context, id pgtype.UUID) ([]GetSessionsByUserRow, error) {
	rows, err := q.db.Query(ctx, getSessionsByUser, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSessionsByUserRow
	for rows.Next() {
		var i GetSessionsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.AccessToken,
			&i.RefreshToken,
			&i.Device,
			&i.Status,
			&i.IpAddress,
			&i.UserAgent,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
			&i.Email,
			&i.Username,
			&i.UserVerified,
			&i.Role,
			&i.CreatedAt_2,
			&i.UpdatedAt_2,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSession = `-- name: UpdateSession :exec
UPDATE diva_session 
SET access_token = $1, refresh_token = $2, device = $3, status = $4, ip_address = $5, user_agent = $6, expires_at = $7, updated_at = NOW() 
WHERE id = $8
`

type UpdateSessionParams struct {
	AccessToken  string
	RefreshToken string
	Device       string
	Status       SessionStatusType
	IpAddress    string
	UserAgent    string
	ExpiresAt    pgtype.Timestamptz
	ID           pgtype.UUID
}

func (q *Queries) UpdateSession(ctx context.Context, arg UpdateSessionParams) error {
	_, err := q.db.Exec(ctx, updateSession,
		arg.AccessToken,
		arg.RefreshToken,
		arg.Device,
		arg.Status,
		arg.IpAddress,
		arg.UserAgent,
		arg.ExpiresAt,
		arg.ID,
	)
	return err
}

const updateSessionStatus = `-- name: UpdateSessionStatus :exec
UPDATE diva_session 
SET  status = $1, updated_at = NOW() 
WHERE id = $2
`

type UpdateSessionStatusParams struct {
	Status SessionStatusType
	ID     pgtype.UUID
}

func (q *Queries) UpdateSessionStatus(ctx context.Context, arg UpdateSessionStatusParams) error {
	_, err := q.db.Exec(ctx, updateSessionStatus, arg.Status, arg.ID)
	return err
}
