// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: session.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :exec
INSERT INTO diva_session (id, user_id, access_token, refresh_token, device, status, ip_address, user_agent, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type CreateSessionParams struct {
	ID           pgtype.UUID
	UserID       pgtype.UUID
	AccessToken  string
	RefreshToken string
	Device       string
	Status       string
	IpAddress    string
	UserAgent    string
	ExpiresAt    pgtype.Timestamptz
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.AccessToken,
		arg.RefreshToken,
		arg.Device,
		arg.Status,
		arg.IpAddress,
		arg.UserAgent,
		arg.ExpiresAt,
	)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM diva_session
WHERE id = $1
`

func (q *Queries) DeleteSession(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSession, id)
	return err
}

const deleteSessionByUserID = `-- name: DeleteSessionByUserID :exec
DELETE FROM diva_session
WHERE user_id = $1
`

func (q *Queries) DeleteSessionByUserID(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSessionByUserID, userID)
	return err
}

const getSessionByID = `-- name: GetSessionByID :one
SELECT
  s.id,
  s.access_token AS access_token,
  s.refresh_token AS refresh_token,
  s.device,
  s.status,
  s.ip_address AS ip_address,
  s.user_agent AS user_agent,
  s.expires_at AS expires_at,
  s.created_at AS created_at,
  s.updated_at AS updated_at,
  u.id AS user_id,
  u.email,
  u.username,
  u.user_verified,
  u.role,
  u.created_at AS u_created_at,
  u.updated_at AS u_updated_at
FROM diva_session s
LEFT JOIN diva_user u ON s.user_id = u.id
WHERE s.id = $1 AND u.deleted_at IS NULL
`

type GetSessionByIDRow struct {
	ID           pgtype.UUID
	AccessToken  string
	RefreshToken string
	Device       string
	Status       string
	IpAddress    string
	UserAgent    string
	ExpiresAt    pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	UserID       pgtype.UUID
	Email        pgtype.Text
	Username     pgtype.Text
	UserVerified pgtype.Bool
	Role         pgtype.Text
	UCreatedAt   pgtype.Timestamptz
	UUpdatedAt   pgtype.Timestamptz
}

func (q *Queries) GetSessionByID(ctx context.Context, id pgtype.UUID) (GetSessionByIDRow, error) {
	row := q.db.QueryRow(ctx, getSessionByID, id)
	var i GetSessionByIDRow
	err := row.Scan(
		&i.ID,
		&i.AccessToken,
		&i.RefreshToken,
		&i.Device,
		&i.Status,
		&i.IpAddress,
		&i.UserAgent,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.Email,
		&i.Username,
		&i.UserVerified,
		&i.Role,
		&i.UCreatedAt,
		&i.UUpdatedAt,
	)
	return i, err
}

const updateSession = `-- name: UpdateSession :exec
UPDATE diva_session 
SET access_token = $1, refresh_token = $2, device = $3, status = $4, ip_address = $5, user_agent = $6, expires_at = $7, updated_at = NOW() 
WHERE id = $8
`

type UpdateSessionParams struct {
	AccessToken  string
	RefreshToken string
	Device       string
	Status       string
	IpAddress    string
	UserAgent    string
	ExpiresAt    pgtype.Timestamptz
	ID           pgtype.UUID
}

func (q *Queries) UpdateSession(ctx context.Context, arg UpdateSessionParams) error {
	_, err := q.db.Exec(ctx, updateSession,
		arg.AccessToken,
		arg.RefreshToken,
		arg.Device,
		arg.Status,
		arg.IpAddress,
		arg.UserAgent,
		arg.ExpiresAt,
		arg.ID,
	)
	return err
}
