// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tag.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countTag = `-- name: CountTag :one
SELECT COUNT(*)
FROM diva_tag
WHERE deleted_at IS NULL
`

func (q *Queries) CountTag(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countTag)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTag = `-- name: CreateTag :exec
INSERT INTO diva_tag (id, tag_name)
VALUES ($1, $2)
`

type CreateTagParams struct {
	ID      pgtype.UUID
	TagName string
}

func (q *Queries) CreateTag(ctx context.Context, arg CreateTagParams) error {
	_, err := q.db.Exec(ctx, createTag, arg.ID, arg.TagName)
	return err
}

const deleteTag = `-- name: DeleteTag :exec
UPDATE diva_tag
SET deleted_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) DeleteTag(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteTag, id)
	return err
}

const getTagByID = `-- name: GetTagByID :one
SELECT id, tag_name, created_at, updated_at, deleted_at FROM diva_tag 
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetTagByID(ctx context.Context, id pgtype.UUID) (DivaTag, error) {
	row := q.db.QueryRow(ctx, getTagByID, id)
	var i DivaTag
	err := row.Scan(
		&i.ID,
		&i.TagName,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listTags = `-- name: ListTags :many
SELECT id, tag_name, created_at, updated_at, deleted_at FROM diva_tag
WHERE deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListTagsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListTags(ctx context.Context, arg ListTagsParams) ([]DivaTag, error) {
	rows, err := q.db.Query(ctx, listTags, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DivaTag
	for rows.Next() {
		var i DivaTag
		if err := rows.Scan(
			&i.ID,
			&i.TagName,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTag = `-- name: UpdateTag :exec
UPDATE diva_tag 
SET tag_name = $1, updated_at = NOW() 
WHERE id = $2
`

type UpdateTagParams struct {
	TagName string
	ID      pgtype.UUID
}

func (q *Queries) UpdateTag(ctx context.Context, arg UpdateTagParams) error {
	_, err := q.db.Exec(ctx, updateTag, arg.TagName, arg.ID)
	return err
}
