// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_preferences.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUserPreferences = `-- name: CreateUserPreferences :exec
insert into diva_user_preferences (
    id,
    user_id,
    device,
    theme,
    onboarding_completed,
    language
) values (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
`

type CreateUserPreferencesParams struct {
	ID                  pgtype.UUID
	UserID              pgtype.UUID
	Device              string
	Theme               ThemeType
	OnboardingCompleted bool
	Language            string
}

func (q *Queries) CreateUserPreferences(ctx context.Context, arg CreateUserPreferencesParams) error {
	_, err := q.db.Exec(ctx, createUserPreferences,
		arg.ID,
		arg.UserID,
		arg.Device,
		arg.Theme,
		arg.OnboardingCompleted,
		arg.Language,
	)
	return err
}

const deletePreferences = `-- name: DeletePreferences :exec
delete from diva_user_preferences
where id = $1
`

func (q *Queries) DeletePreferences(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deletePreferences, id)
	return err
}

const deletePreferencesByUser = `-- name: DeletePreferencesByUser :exec
delete from diva_user_preferences
where user_id = $1
`

func (q *Queries) DeletePreferencesByUser(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deletePreferencesByUser, userID)
	return err
}

const getPreferencesByID = `-- name: GetPreferencesByID :one
select
    up.id as id,
    up.user_id,
    up.device,
    up.theme,
    up.onboarding_completed,
    up.language,
    up.last_sync_at,
    up.created_at,
    up.updated_at
from diva_user_preferences up
where up.id = $1
`

func (q *Queries) GetPreferencesByID(ctx context.Context, id pgtype.UUID) (DivaUserPreference, error) {
	row := q.db.QueryRow(ctx, getPreferencesByID, id)
	var i DivaUserPreference
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Device,
		&i.Theme,
		&i.OnboardingCompleted,
		&i.Language,
		&i.LastSyncAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPreferencesByUser = `-- name: GetPreferencesByUser :many
select
    up.id as id,
    up.user_id,
    up.device,
    up.theme,
    up.onboarding_completed,
    up.language,
    up.last_sync_at,
    up.created_at,
    up.updated_at
from diva_user_preferences up
where up.user_id = $1
`

func (q *Queries) GetPreferencesByUser(ctx context.Context, userID pgtype.UUID) ([]DivaUserPreference, error) {
	rows, err := q.db.Query(ctx, getPreferencesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DivaUserPreference
	for rows.Next() {
		var i DivaUserPreference
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Device,
			&i.Theme,
			&i.OnboardingCompleted,
			&i.Language,
			&i.LastSyncAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserPreferences = `-- name: UpdateUserPreferences :exec
update diva_user_preferences set
    theme = $1,
    language = $2,
    last_sync_at = now(),
    updated_at = now()
where id = $3
`

type UpdateUserPreferencesParams struct {
	Theme    ThemeType
	Language string
	ID       pgtype.UUID
}

func (q *Queries) UpdateUserPreferences(ctx context.Context, arg UpdateUserPreferencesParams) error {
	_, err := q.db.Exec(ctx, updateUserPreferences, arg.Theme, arg.Language, arg.ID)
	return err
}
