// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_preferences.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUserPreferences = `-- name: CreateUserPreferences :exec
INSERT INTO diva_user_preferences (id, user_id, theme, onboarding_completed, language, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateUserPreferencesParams struct {
	ID                  pgtype.UUID
	UserID              pgtype.UUID
	Theme               ThemeType
	OnboardingCompleted bool
	Language            string
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
}

func (q *Queries) CreateUserPreferences(ctx context.Context, arg CreateUserPreferencesParams) error {
	_, err := q.db.Exec(ctx, createUserPreferences,
		arg.ID,
		arg.UserID,
		arg.Theme,
		arg.OnboardingCompleted,
		arg.Language,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const updateUserPreferences = `-- name: UpdateUserPreferences :exec
UPDATE diva_user_preferences 
SET theme = $1, language = $2, last_sync_at = NOW(), updated_at = $3
WHERE id = $4
`

type UpdateUserPreferencesParams struct {
	Theme     ThemeType
	Language  string
	UpdatedAt pgtype.Timestamptz
	ID        pgtype.UUID
}

func (q *Queries) UpdateUserPreferences(ctx context.Context, arg UpdateUserPreferencesParams) error {
	_, err := q.db.Exec(ctx, updateUserPreferences,
		arg.Theme,
		arg.Language,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
