// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const count = `-- name: Count :one
SELECT COUNT(*) FROM diva_user
`

func (q *Queries) Count(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, count)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO diva_user (id, email, username, password_hash, birth_date, phone_number, alias, avatar, bio, user_verified, role)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
`

type CreateUserParams struct {
	ID           pgtype.UUID
	Email        string
	Username     string
	PasswordHash string
	BirthDate    pgtype.Timestamptz
	PhoneNumber  string
	Alias        string
	Avatar       string
	Bio          string
	UserVerified bool
	Role         string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.Username,
		arg.PasswordHash,
		arg.BirthDate,
		arg.PhoneNumber,
		arg.Alias,
		arg.Avatar,
		arg.Bio,
		arg.UserVerified,
		arg.Role,
	)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
UPDATE diva_user 
SET deleted_at = NOW() 
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) DeleteUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUserByID = `-- name: GetUserByID :one
SELECT
  u.id,
  u.email,
  u.username,
  u.password_hash AS password_hash,
  u.alias,
  u.avatar,
  u.bio,
  u.user_verified AS user_verified,
  u.role,
  u.created_at AS created_at,
  u.updated_at AS updated_at,
  u.deleted_at AS deleted_at
FROM diva_user u
WHERE u.id = $1 AND u.deleted_at IS NULL
`

type GetUserByIDRow struct {
	ID           pgtype.UUID
	Email        string
	Username     string
	PasswordHash string
	Alias        string
	Avatar       string
	Bio          string
	UserVerified bool
	Role         string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	DeletedAt    pgtype.Timestamptz
}

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.Alias,
		&i.Avatar,
		&i.Bio,
		&i.UserVerified,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT
  id,
  email,
  username,
  password_hash AS password_hash,
  alias,
  avatar,
  bio,
  user_verified AS user_verified,
  role,
  created_at AS created_at,
  updated_at AS updated_at,
  deleted_at AS deleted_at
FROM diva_user
WHERE username = $1 OR email = $2 AND deleted_at IS NULL
`

type GetUserByUsernameParams struct {
	Username string
	Email    string
}

type GetUserByUsernameRow struct {
	ID           pgtype.UUID
	Email        string
	Username     string
	PasswordHash string
	Alias        string
	Avatar       string
	Bio          string
	UserVerified bool
	Role         string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	DeletedAt    pgtype.Timestamptz
}

func (q *Queries) GetUserByUsername(ctx context.Context, arg GetUserByUsernameParams) (GetUserByUsernameRow, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, arg.Username, arg.Email)
	var i GetUserByUsernameRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.Alias,
		&i.Avatar,
		&i.Bio,
		&i.UserVerified,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT
  u.id,
  u.email,
  u.username,
  u.password_hash AS password_hash,
  u.alias,
  u.avatar,
  u.bio,
  u.user_verified AS user_verified,
  u.role,
  u.created_at AS created_at,
  u.updated_at AS updated_at,
  u.deleted_at AS deleted_at
FROM diva_user u
WHERE u.deleted_at IS NULL
LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit  int32
	Offset int32
}

type ListUsersRow struct {
	ID           pgtype.UUID
	Email        string
	Username     string
	PasswordHash string
	Alias        string
	Avatar       string
	Bio          string
	UserVerified bool
	Role         string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	DeletedAt    pgtype.Timestamptz
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Username,
			&i.PasswordHash,
			&i.Alias,
			&i.Avatar,
			&i.Bio,
			&i.UserVerified,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEmail = `-- name: UpdateEmail :exec
UPDATE diva_user
SET email = $1
WHERE id = $2 AND deleted_at IS NULL
`

type UpdateEmailParams struct {
	Email string
	ID    pgtype.UUID
}

func (q *Queries) UpdateEmail(ctx context.Context, arg UpdateEmailParams) error {
	_, err := q.db.Exec(ctx, updateEmail, arg.Email, arg.ID)
	return err
}

const updatePassword = `-- name: UpdatePassword :exec
UPDATE diva_user
SET password_hash = $1
WHERE id = $2 AND deleted_at IS NULL
`

type UpdatePasswordParams struct {
	PasswordHash string
	ID           pgtype.UUID
}

func (q *Queries) UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error {
	_, err := q.db.Exec(ctx, updatePassword, arg.PasswordHash, arg.ID)
	return err
}

const updatePhoneNumber = `-- name: UpdatePhoneNumber :exec
UPDATE diva_user
SET phone_number = $1
WHERE id = $2 AND deleted_at IS NULL
`

type UpdatePhoneNumberParams struct {
	PhoneNumber string
	ID          pgtype.UUID
}

func (q *Queries) UpdatePhoneNumber(ctx context.Context, arg UpdatePhoneNumberParams) error {
	_, err := q.db.Exec(ctx, updatePhoneNumber, arg.PhoneNumber, arg.ID)
	return err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE diva_user 
SET alias = $1, avatar = $2, bio = $3, updated_at = NOW()
WHERE id = $4 AND deleted_at IS NULL
`

type UpdateUserParams struct {
	Alias  string
	Avatar string
	Bio    string
	ID     pgtype.UUID
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.Exec(ctx, updateUser,
		arg.Alias,
		arg.Avatar,
		arg.Bio,
		arg.ID,
	)
	return err
}

const updateUsername = `-- name: UpdateUsername :exec
UPDATE diva_user
SET username = $1
WHERE id = $2 AND deleted_at IS NULL
`

type UpdateUsernameParams struct {
	Username string
	ID       pgtype.UUID
}

func (q *Queries) UpdateUsername(ctx context.Context, arg UpdateUsernameParams) error {
	_, err := q.db.Exec(ctx, updateUsername, arg.Username, arg.ID)
	return err
}

const updateVerified = `-- name: UpdateVerified :exec
UPDATE diva_user
SET user_verified = $1
WHERE id = $2 AND deleted_at IS NULL
`

type UpdateVerifiedParams struct {
	UserVerified bool
	ID           pgtype.UUID
}

func (q *Queries) UpdateVerified(ctx context.Context, arg UpdateVerifiedParams) error {
	_, err := q.db.Exec(ctx, updateVerified, arg.UserVerified, arg.ID)
	return err
}
