// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_actions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUserAction = `-- name: CreateUserAction :exec
INSERT INTO diva_user_pending_actions (id, user_id, action_name)
VALUES ($1, $2, $3)
`

type CreateUserActionParams struct {
	ID         pgtype.UUID
	UserID     pgtype.UUID
	ActionName string
}

func (q *Queries) CreateUserAction(ctx context.Context, arg CreateUserActionParams) error {
	_, err := q.db.Exec(ctx, createUserAction, arg.ID, arg.UserID, arg.ActionName)
	return err
}

const deleteUserAction = `-- name: DeleteUserAction :exec
delete from diva_user_pending_actions
where user_id = $1 and action_name = $2
`

type DeleteUserActionParams struct {
	UserID     pgtype.UUID
	ActionName string
}

func (q *Queries) DeleteUserAction(ctx context.Context, arg DeleteUserActionParams) error {
	_, err := q.db.Exec(ctx, deleteUserAction, arg.UserID, arg.ActionName)
	return err
}

const deleteUserActions = `-- name: DeleteUserActions :exec
delete from diva_user_pending_actions
where user_id = $1
`

func (q *Queries) DeleteUserActions(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserActions, userID)
	return err
}

const getUserAction = `-- name: GetUserAction :one
select id, user_id, action_name
from diva_user_pending_actions
where action_name = $1 and user_id = $2
`

type GetUserActionParams struct {
	ActionName string
	UserID     pgtype.UUID
}

func (q *Queries) GetUserAction(ctx context.Context, arg GetUserActionParams) (DivaUserPendingAction, error) {
	row := q.db.QueryRow(ctx, getUserAction, arg.ActionName, arg.UserID)
	var i DivaUserPendingAction
	err := row.Scan(&i.ID, &i.UserID, &i.ActionName)
	return i, err
}

const getUserActions = `-- name: GetUserActions :many
select id, user_id, action_name
from diva_user_pending_actions
where user_id = $1
`

func (q *Queries) GetUserActions(ctx context.Context, userID pgtype.UUID) ([]DivaUserPendingAction, error) {
	rows, err := q.db.Query(ctx, getUserActions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DivaUserPendingAction
	for rows.Next() {
		var i DivaUserPendingAction
		if err := rows.Scan(&i.ID, &i.UserID, &i.ActionName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
