// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_profile.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUserProfile = `-- name: CreateUserProfile :exec
insert into diva_user_profile (
    user_id,
    first_name,
    last_name,
    birth_date,
    phone_number,
    alias,
    bio
) values (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
`

type CreateUserProfileParams struct {
	UserID      pgtype.UUID
	FirstName   string
	LastName    string
	BirthDate   pgtype.Timestamptz
	PhoneNumber string
	Alias       string
	Bio         string
}

func (q *Queries) CreateUserProfile(ctx context.Context, arg CreateUserProfileParams) error {
	_, err := q.db.Exec(ctx, createUserProfile,
		arg.UserID,
		arg.FirstName,
		arg.LastName,
		arg.BirthDate,
		arg.PhoneNumber,
		arg.Alias,
		arg.Bio,
	)
	return err
}

const deleteUserProfile = `-- name: DeleteUserProfile :exec
delete from diva_user_profile
where user_id = $1
`

func (q *Queries) DeleteUserProfile(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserProfile, userID)
	return err
}

const getUserProfileByUserID = `-- name: GetUserProfileByUserID :one
select
    up.user_id as userId,
    up.first_name as firstName,
    up.last_name as lastName,
    up.birth_date as birthDate,
    up.phone_number as phoneNumber,
    up.alias,
    up.bio
from diva_user_profile up
where up.user_id = $1
`

type GetUserProfileByUserIDRow struct {
	Userid      pgtype.UUID
	Firstname   string
	Lastname    string
	Birthdate   pgtype.Timestamptz
	Phonenumber string
	Alias       string
	Bio         string
}

func (q *Queries) GetUserProfileByUserID(ctx context.Context, userID pgtype.UUID) (GetUserProfileByUserIDRow, error) {
	row := q.db.QueryRow(ctx, getUserProfileByUserID, userID)
	var i GetUserProfileByUserIDRow
	err := row.Scan(
		&i.Userid,
		&i.Firstname,
		&i.Lastname,
		&i.Birthdate,
		&i.Phonenumber,
		&i.Alias,
		&i.Bio,
	)
	return i, err
}

const updatePhoneNumber = `-- name: UpdatePhoneNumber :exec
update diva_user_profile
set
    phone_number = $1
where user_id = $2
`

type UpdatePhoneNumberParams struct {
	PhoneNumber string
	UserID      pgtype.UUID
}

func (q *Queries) UpdatePhoneNumber(ctx context.Context, arg UpdatePhoneNumberParams) error {
	_, err := q.db.Exec(ctx, updatePhoneNumber, arg.PhoneNumber, arg.UserID)
	return err
}

const updateUserProfile = `-- name: UpdateUserProfile :exec
update diva_user_profile
set
    first_name = $1,
    last_name = $2,
    birth_date = $3,
    alias = $4,
    bio = $5
where user_id = $6
`

type UpdateUserProfileParams struct {
	FirstName string
	LastName  string
	BirthDate pgtype.Timestamptz
	Alias     string
	Bio       string
	UserID    pgtype.UUID
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) error {
	_, err := q.db.Exec(ctx, updateUserProfile,
		arg.FirstName,
		arg.LastName,
		arg.BirthDate,
		arg.Alias,
		arg.Bio,
		arg.UserID,
	)
	return err
}
