// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_preferences.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUserPreferences = `-- name: CreateUserPreferences :exec
insert into diva_user_preferences (
    id,
    user_id,
    device,
    theme,
    onboarding_completed,
    language,
    created_at,
    updated_at
) values (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
`

type CreateUserPreferencesParams struct {
	ID                  pgtype.UUID
	UserID              pgtype.UUID
	Device              string
	Theme               ThemeType
	OnboardingCompleted bool
	Language            string
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
}

func (q *Queries) CreateUserPreferences(ctx context.Context, arg CreateUserPreferencesParams) error {
	_, err := q.db.Exec(ctx, createUserPreferences,
		arg.ID,
		arg.UserID,
		arg.Device,
		arg.Theme,
		arg.OnboardingCompleted,
		arg.Language,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deletePreferences = `-- name: DeletePreferences :exec
delete from diva_user_preferences
where id = $1
`

func (q *Queries) DeletePreferences(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deletePreferences, id)
	return err
}

const deletePreferencesByUser = `-- name: DeletePreferencesByUser :exec
delete from diva_user_preferences
where user_id = $1
`

func (q *Queries) DeletePreferencesByUser(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deletePreferencesByUser, userID)
	return err
}

const getPreferencesByDevice = `-- name: GetPreferencesByDevice :one
select
    up.id as id,
    up.user_id as userId,
    up.device,
    up.theme,
    up.onboarding_completed as onboardingCompleted,
    up.language,
    up.last_sync_at as lastSyncAt,
    up.created_at as createdAt,
    up.updated_at as updatedAt
from diva_user_preferences up
where up.device = $1
`

type GetPreferencesByDeviceRow struct {
	ID                  pgtype.UUID
	Userid              pgtype.UUID
	Device              string
	Theme               ThemeType
	Onboardingcompleted bool
	Language            string
	Lastsyncat          pgtype.Timestamptz
	Createdat           pgtype.Timestamptz
	Updatedat           pgtype.Timestamptz
}

func (q *Queries) GetPreferencesByDevice(ctx context.Context, device string) (GetPreferencesByDeviceRow, error) {
	row := q.db.QueryRow(ctx, getPreferencesByDevice, device)
	var i GetPreferencesByDeviceRow
	err := row.Scan(
		&i.ID,
		&i.Userid,
		&i.Device,
		&i.Theme,
		&i.Onboardingcompleted,
		&i.Language,
		&i.Lastsyncat,
		&i.Createdat,
		&i.Updatedat,
	)
	return i, err
}

const getPreferencesByID = `-- name: GetPreferencesByID :one
select
    up.id as id,
    up.user_id as userId,
    up.device,
    up.theme,
    up.onboarding_completed as onboardingCompleted,
    up.language,
    up.last_sync_at as lastSyncAt,
    up.created_at as createdAt,
    up.updated_at as updatedAt
from diva_user_preferences up
where up.id = $1
`

type GetPreferencesByIDRow struct {
	ID                  pgtype.UUID
	Userid              pgtype.UUID
	Device              string
	Theme               ThemeType
	Onboardingcompleted bool
	Language            string
	Lastsyncat          pgtype.Timestamptz
	Createdat           pgtype.Timestamptz
	Updatedat           pgtype.Timestamptz
}

func (q *Queries) GetPreferencesByID(ctx context.Context, id pgtype.UUID) (GetPreferencesByIDRow, error) {
	row := q.db.QueryRow(ctx, getPreferencesByID, id)
	var i GetPreferencesByIDRow
	err := row.Scan(
		&i.ID,
		&i.Userid,
		&i.Device,
		&i.Theme,
		&i.Onboardingcompleted,
		&i.Language,
		&i.Lastsyncat,
		&i.Createdat,
		&i.Updatedat,
	)
	return i, err
}

const getPreferencesByUser = `-- name: GetPreferencesByUser :many
select
    up.id as id,
    up.user_id as userId,
    up.device,
    up.theme,
    up.onboarding_completed as onboardingCompleted,
    up.language,
    up.last_sync_at as lastSyncAt,
    up.created_at as createdAt,
    up.updated_at as updatedAt
from diva_user_preferences up
where up.user_id = $1
`

type GetPreferencesByUserRow struct {
	ID                  pgtype.UUID
	Userid              pgtype.UUID
	Device              string
	Theme               ThemeType
	Onboardingcompleted bool
	Language            string
	Lastsyncat          pgtype.Timestamptz
	Createdat           pgtype.Timestamptz
	Updatedat           pgtype.Timestamptz
}

func (q *Queries) GetPreferencesByUser(ctx context.Context, userID pgtype.UUID) ([]GetPreferencesByUserRow, error) {
	rows, err := q.db.Query(ctx, getPreferencesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPreferencesByUserRow
	for rows.Next() {
		var i GetPreferencesByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Userid,
			&i.Device,
			&i.Theme,
			&i.Onboardingcompleted,
			&i.Language,
			&i.Lastsyncat,
			&i.Createdat,
			&i.Updatedat,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserPreferences = `-- name: UpdateUserPreferences :exec
update diva_user_preferences
set
    theme = $1,
    language = $2,
    last_sync_at = now(),
    updated_at = $3
where id = $4
`

type UpdateUserPreferencesParams struct {
	Theme     ThemeType
	Language  string
	UpdatedAt pgtype.Timestamptz
	ID        pgtype.UUID
}

func (q *Queries) UpdateUserPreferences(ctx context.Context, arg UpdateUserPreferencesParams) error {
	_, err := q.db.Exec(ctx, updateUserPreferences,
		arg.Theme,
		arg.Language,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
