// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_profile.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUserProfile = `-- name: CreateUserProfile :exec
insert into diva_user_profile (
    user_id,
    first_name,
    last_name,
    birth_date,
    alias,
    bio
) values (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
`

type CreateUserProfileParams struct {
	UserID    pgtype.UUID
	FirstName string
	LastName  string
	BirthDate pgtype.Timestamptz
	Alias     string
	Bio       string
}

func (q *Queries) CreateUserProfile(ctx context.Context, arg CreateUserProfileParams) error {
	_, err := q.db.Exec(ctx, createUserProfile,
		arg.UserID,
		arg.FirstName,
		arg.LastName,
		arg.BirthDate,
		arg.Alias,
		arg.Bio,
	)
	return err
}

const getUserProfileByUserID = `-- name: GetUserProfileByUserID :one
select
    up.user_id,
    up.first_name,
    up.last_name,
    up.birth_date,
    up.alias,
    up.bio,
    up.avatar,
    up.updated_at
from diva_user_profile up
where up.user_id = $1
`

func (q *Queries) GetUserProfileByUserID(ctx context.Context, userID pgtype.UUID) (DivaUserProfile, error) {
	row := q.db.QueryRow(ctx, getUserProfileByUserID, userID)
	var i DivaUserProfile
	err := row.Scan(
		&i.UserID,
		&i.FirstName,
		&i.LastName,
		&i.BirthDate,
		&i.Alias,
		&i.Bio,
		&i.Avatar,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserProfile = `-- name: UpdateUserProfile :exec
update diva_user_profile set
    first_name = $1,
    last_name = $2,
    birth_date = $3,
    alias = $4,
    bio = $5,
    updated_at = now()
where user_id = $6
`

type UpdateUserProfileParams struct {
	FirstName string
	LastName  string
	BirthDate pgtype.Timestamptz
	Alias     string
	Bio       string
	UserID    pgtype.UUID
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) error {
	_, err := q.db.Exec(ctx, updateUserProfile,
		arg.FirstName,
		arg.LastName,
		arg.BirthDate,
		arg.Alias,
		arg.Bio,
		arg.UserID,
	)
	return err
}

const updateUserProfileAvatar = `-- name: UpdateUserProfileAvatar :exec
update diva_user_profile set
    avatar = $1,
    updated_at = now()
where user_id = $2
`

type UpdateUserProfileAvatarParams struct {
	Avatar string
	UserID pgtype.UUID
}

func (q *Queries) UpdateUserProfileAvatar(ctx context.Context, arg UpdateUserProfileAvatarParams) error {
	_, err := q.db.Exec(ctx, updateUserProfileAvatar, arg.Avatar, arg.UserID)
	return err
}
