// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_verification.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createVerification = `-- name: CreateVerification :exec
insert into diva_action_verification (
    action_id,
    token,
    verified,
    expires_at,
    used_at
) values (
    $1,
    $2,
    $3,
    $4,
    $5
)
`

type CreateVerificationParams struct {
	ActionID  pgtype.UUID
	Token     string
	Verified  bool
	ExpiresAt pgtype.Timestamptz
	UsedAt    pgtype.Timestamptz
}

func (q *Queries) CreateVerification(ctx context.Context, arg CreateVerificationParams) error {
	_, err := q.db.Exec(ctx, createVerification,
		arg.ActionID,
		arg.Token,
		arg.Verified,
		arg.ExpiresAt,
		arg.UsedAt,
	)
	return err
}

const deleteVerification = `-- name: DeleteVerification :exec
delete from diva_action_verification
where action_id = $1
`

func (q *Queries) DeleteVerification(ctx context.Context, actionID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteVerification, actionID)
	return err
}

const getVerification = `-- name: GetVerification :one
select v.action_id, v.token, v.expires_at, v.used_at, v.verified
from diva_action_verification v
where v.action_id = $1
`

type GetVerificationRow struct {
	ActionID  pgtype.UUID
	Token     string
	ExpiresAt pgtype.Timestamptz
	UsedAt    pgtype.Timestamptz
	Verified  bool
}

func (q *Queries) GetVerification(ctx context.Context, actionID pgtype.UUID) (GetVerificationRow, error) {
	row := q.db.QueryRow(ctx, getVerification, actionID)
	var i GetVerificationRow
	err := row.Scan(
		&i.ActionID,
		&i.Token,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.Verified,
	)
	return i, err
}

const updateVerification = `-- name: UpdateVerification :exec
update diva_action_verification set
    verified = $1,
    used_at = now()
where action_id = $2
`

type UpdateVerificationParams struct {
	Verified bool
	ActionID pgtype.UUID
}

func (q *Queries) UpdateVerification(ctx context.Context, arg UpdateVerificationParams) error {
	_, err := q.db.Exec(ctx, updateVerification, arg.Verified, arg.ActionID)
	return err
}
