// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_action.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUserAction = `-- name: CreateUserAction :exec
insert into diva_user_action (
    id,
    name,
    user_id
) values (
    $1,
    $2,
    $3
) on conflict (user_id, name) do nothing
`

type CreateUserActionParams struct {
	ID     pgtype.UUID
	Name   string
	UserID pgtype.UUID
}

func (q *Queries) CreateUserAction(ctx context.Context, arg CreateUserActionParams) error {
	_, err := q.db.Exec(ctx, createUserAction, arg.ID, arg.Name, arg.UserID)
	return err
}

const deleteUserAction = `-- name: DeleteUserAction :exec
delete from diva_user_action
where id = $1
`

func (q *Queries) DeleteUserAction(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserAction, id)
	return err
}

const getUserActionByID = `-- name: GetUserActionByID :one
select
    ua.id as id,
    ua.name,
    ua.user_id as userId
from diva_user_action ua
where ua.id = $1
`

type GetUserActionByIDRow struct {
	ID     pgtype.UUID
	Name   string
	Userid pgtype.UUID
}

func (q *Queries) GetUserActionByID(ctx context.Context, id pgtype.UUID) (GetUserActionByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserActionByID, id)
	var i GetUserActionByIDRow
	err := row.Scan(&i.ID, &i.Name, &i.Userid)
	return i, err
}

const getUserActionByUserAndName = `-- name: GetUserActionByUserAndName :one
select
    ua.id as id,
    ua.name,
    ua.user_id as userId
from diva_user_action ua
where ua.user_id = $1 and ua.name = $2
`

type GetUserActionByUserAndNameParams struct {
	UserID pgtype.UUID
	Name   string
}

type GetUserActionByUserAndNameRow struct {
	ID     pgtype.UUID
	Name   string
	Userid pgtype.UUID
}

func (q *Queries) GetUserActionByUserAndName(ctx context.Context, arg GetUserActionByUserAndNameParams) (GetUserActionByUserAndNameRow, error) {
	row := q.db.QueryRow(ctx, getUserActionByUserAndName, arg.UserID, arg.Name)
	var i GetUserActionByUserAndNameRow
	err := row.Scan(&i.ID, &i.Name, &i.Userid)
	return i, err
}
