// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_verification.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createVerification = `-- name: CreateVerification :exec
insert into diva_action_verification (
    action_id,
    token,
    expires_at
) values (
    $1,
    $2,
    $3
)
`

type CreateVerificationParams struct {
	ActionID  pgtype.UUID
	Token     string
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateVerification(ctx context.Context, arg CreateVerificationParams) error {
	_, err := q.db.Exec(ctx, createVerification, arg.ActionID, arg.Token, arg.ExpiresAt)
	return err
}

const deleteVerification = `-- name: DeleteVerification :exec
delete from diva_action_verification
where action_id = $1
`

func (q *Queries) DeleteVerification(ctx context.Context, actionID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteVerification, actionID)
	return err
}

const getVerification = `-- name: GetVerification :one
select v.action_id, v.token, v.expires_at
from diva_action_verification v
where v.action_id = $1
`

func (q *Queries) GetVerification(ctx context.Context, actionID pgtype.UUID) (DivaActionVerification, error) {
	row := q.db.QueryRow(ctx, getVerification, actionID)
	var i DivaActionVerification
	err := row.Scan(&i.ActionID, &i.Token, &i.ExpiresAt)
	return i, err
}
