// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_permissions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUserPermission = `-- name: CreateUserPermission :exec
INSERT INTO diva_user_permissions (permission_id, user_id, granted_by, granted, expires_at)
VALUES ($1, $2, $3, $4, $5)
`

type CreateUserPermissionParams struct {
	PermissionID pgtype.UUID
	UserID       pgtype.UUID
	GrantedBy    pgtype.UUID
	Granted      bool
	ExpiresAt    pgtype.Timestamptz
}

func (q *Queries) CreateUserPermission(ctx context.Context, arg CreateUserPermissionParams) error {
	_, err := q.db.Exec(ctx, createUserPermission,
		arg.PermissionID,
		arg.UserID,
		arg.GrantedBy,
		arg.Granted,
		arg.ExpiresAt,
	)
	return err
}

const deleteUserPermission = `-- name: DeleteUserPermission :exec
delete from diva_user_permissions
where permission_id = $1 and user_id = $2
`

type DeleteUserPermissionParams struct {
	PermissionID pgtype.UUID
	UserID       pgtype.UUID
}

func (q *Queries) DeleteUserPermission(ctx context.Context, arg DeleteUserPermissionParams) error {
	_, err := q.db.Exec(ctx, deleteUserPermission, arg.PermissionID, arg.UserID)
	return err
}

const deleteUserPermissions = `-- name: DeleteUserPermissions :exec
delete from diva_user_permissions
where user_id = $1
`

func (q *Queries) DeleteUserPermissions(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserPermissions, userID)
	return err
}

const getUserPermissions = `-- name: GetUserPermissions :many
select permission_id, user_id, granted_by, granted, granted_at, expires_at, updated_at
from diva_user_permissions
where user_id = $1
`

func (q *Queries) GetUserPermissions(ctx context.Context, userID pgtype.UUID) ([]DivaUserPermission, error) {
	rows, err := q.db.Query(ctx, getUserPermissions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DivaUserPermission
	for rows.Next() {
		var i DivaUserPermission
		if err := rows.Scan(
			&i.PermissionID,
			&i.UserID,
			&i.GrantedBy,
			&i.Granted,
			&i.GrantedAt,
			&i.ExpiresAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserPermission = `-- name: UpdateUserPermission :exec
UPDATE diva_user_permissions
SET granted = $1, expires_at = $2, updated_at = NOW()
WHERE permission_id = $3 AND user_id = $4
`

type UpdateUserPermissionParams struct {
	Granted      bool
	ExpiresAt    pgtype.Timestamptz
	PermissionID pgtype.UUID
	UserID       pgtype.UUID
}

func (q *Queries) UpdateUserPermission(ctx context.Context, arg UpdateUserPermissionParams) error {
	_, err := q.db.Exec(ctx, updateUserPermission,
		arg.Granted,
		arg.ExpiresAt,
		arg.PermissionID,
		arg.UserID,
	)
	return err
}
