// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_permissions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUserPermission = `-- name: CreateUserPermission :exec
insert into diva_user_permissions (
    permission_id,
    user_id,
    granted_by,
    granted,
    expires_at
) values (
    $1,
    $2,
    $3,
    $4,
    $5
) on conflict (permission_id, user_id) do nothing
`

type CreateUserPermissionParams struct {
	PermissionID pgtype.UUID
	UserID       pgtype.UUID
	GrantedBy    pgtype.UUID
	Granted      bool
	ExpiresAt    pgtype.Timestamptz
}

func (q *Queries) CreateUserPermission(ctx context.Context, arg CreateUserPermissionParams) error {
	_, err := q.db.Exec(ctx, createUserPermission,
		arg.PermissionID,
		arg.UserID,
		arg.GrantedBy,
		arg.Granted,
		arg.ExpiresAt,
	)
	return err
}

const deleteAllUserPermissions = `-- name: DeleteAllUserPermissions :exec
delete from diva_user_permissions
where user_id = $1
`

func (q *Queries) DeleteAllUserPermissions(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAllUserPermissions, userID)
	return err
}

const deleteUserPermission = `-- name: DeleteUserPermission :exec
delete from diva_user_permissions
where permission_id = $1 and user_id = $2
`

type DeleteUserPermissionParams struct {
	PermissionID pgtype.UUID
	UserID       pgtype.UUID
}

func (q *Queries) DeleteUserPermission(ctx context.Context, arg DeleteUserPermissionParams) error {
	_, err := q.db.Exec(ctx, deleteUserPermission, arg.PermissionID, arg.UserID)
	return err
}

const getUserPermission = `-- name: GetUserPermission :one
select
    up.permission_id,
    up.user_id,
    up.granted_by,
    up.granted,
    up.granted_at,
    up.expires_at,
    up.updated_at
from diva_user_permissions up
where up.permission_id = $1 and up.user_id = $2
`

type GetUserPermissionParams struct {
	PermissionID pgtype.UUID
	UserID       pgtype.UUID
}

func (q *Queries) GetUserPermission(ctx context.Context, arg GetUserPermissionParams) (DivaUserPermission, error) {
	row := q.db.QueryRow(ctx, getUserPermission, arg.PermissionID, arg.UserID)
	var i DivaUserPermission
	err := row.Scan(
		&i.PermissionID,
		&i.UserID,
		&i.GrantedBy,
		&i.Granted,
		&i.GrantedAt,
		&i.ExpiresAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserPermissions = `-- name: GetUserPermissions :many
select
    up.permission_id,
    up.user_id,
    up.granted_by,
    up.granted,
    up.granted_at,
    up.expires_at,
    up.updated_at
from diva_user_permissions up
where up.user_id = $1 and up.granted = true
`

func (q *Queries) GetUserPermissions(ctx context.Context, userID pgtype.UUID) ([]DivaUserPermission, error) {
	rows, err := q.db.Query(ctx, getUserPermissions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DivaUserPermission
	for rows.Next() {
		var i DivaUserPermission
		if err := rows.Scan(
			&i.PermissionID,
			&i.UserID,
			&i.GrantedBy,
			&i.Granted,
			&i.GrantedAt,
			&i.ExpiresAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserPermission = `-- name: UpdateUserPermission :exec
update diva_user_permissions
set
    granted = $1,
    expires_at = $2,
    updated_at = now()
where permission_id = $3 and user_id = $4
`

type UpdateUserPermissionParams struct {
	Granted      bool
	ExpiresAt    pgtype.Timestamptz
	PermissionID pgtype.UUID
	UserID       pgtype.UUID
}

func (q *Queries) UpdateUserPermission(ctx context.Context, arg UpdateUserPermissionParams) error {
	_, err := q.db.Exec(ctx, updateUserPermission,
		arg.Granted,
		arg.ExpiresAt,
		arg.PermissionID,
		arg.UserID,
	)
	return err
}
