// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_action_verification.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createVerification = `-- name: CreateVerification :exec
insert into diva_user_action_verification (
    action_id,
    token,
    expires_at
) values (
    $1,
    $2,
    $3
)
`

type CreateVerificationParams struct {
	ActionID  pgtype.UUID
	Token     string
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateVerification(ctx context.Context, arg CreateVerificationParams) error {
	_, err := q.db.Exec(ctx, createVerification, arg.ActionID, arg.Token, arg.ExpiresAt)
	return err
}

const deleteVerification = `-- name: DeleteVerification :exec
delete from diva_user_action_verification
where action_id = $1 and token = $2
`

type DeleteVerificationParams struct {
	ActionID pgtype.UUID
	Token    string
}

func (q *Queries) DeleteVerification(ctx context.Context, arg DeleteVerificationParams) error {
	_, err := q.db.Exec(ctx, deleteVerification, arg.ActionID, arg.Token)
	return err
}

const deleteVerificationByActionID = `-- name: DeleteVerificationByActionID :exec
delete from diva_user_action_verification
where action_id = $1
`

func (q *Queries) DeleteVerificationByActionID(ctx context.Context, actionID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteVerificationByActionID, actionID)
	return err
}

const getActionVerification = `-- name: GetActionVerification :one
select 
    v.token,
    v.expires_at as expiresat
from diva_user_action_verification v
where v.action_id = $1 and v.token = $2
`

type GetActionVerificationParams struct {
	ActionID pgtype.UUID
	Token    string
}

type GetActionVerificationRow struct {
	Token     string
	Expiresat pgtype.Timestamptz
}

func (q *Queries) GetActionVerification(ctx context.Context, arg GetActionVerificationParams) (GetActionVerificationRow, error) {
	row := q.db.QueryRow(ctx, getActionVerification, arg.ActionID, arg.Token)
	var i GetActionVerificationRow
	err := row.Scan(&i.Token, &i.Expiresat)
	return i, err
}
