// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_actions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUserPendingAction = `-- name: CreateUserPendingAction :exec
INSERT INTO diva_user_pending_actions (user_id, action_name)
VALUES ($1, $2)
`

type CreateUserPendingActionParams struct {
	UserID     pgtype.UUID
	ActionName string
}

func (q *Queries) CreateUserPendingAction(ctx context.Context, arg CreateUserPendingActionParams) error {
	_, err := q.db.Exec(ctx, createUserPendingAction, arg.UserID, arg.ActionName)
	return err
}

const deleteUserPendingAction = `-- name: DeleteUserPendingAction :exec
DELETE FROM diva_user_pending_actions
WHERE user_id = $1 AND action_name = $2
`

type DeleteUserPendingActionParams struct {
	UserID     pgtype.UUID
	ActionName string
}

func (q *Queries) DeleteUserPendingAction(ctx context.Context, arg DeleteUserPendingActionParams) error {
	_, err := q.db.Exec(ctx, deleteUserPendingAction, arg.UserID, arg.ActionName)
	return err
}

const getUserPendingActions = `-- name: GetUserPendingActions :many
SELECT user_id, action_name
FROM diva_user_pending_actions
WHERE user_id = $1
`

func (q *Queries) GetUserPendingActions(ctx context.Context, userID pgtype.UUID) ([]DivaUserPendingAction, error) {
	rows, err := q.db.Query(ctx, getUserPendingActions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DivaUserPendingAction
	for rows.Next() {
		var i DivaUserPendingAction
		if err := rows.Scan(&i.UserID, &i.ActionName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
