// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :exec
insert into diva_user (
    id,
    username,
    email,
    password_hash,
    verified,
    role,
    created_at,
    updated_at
) values (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
`

type CreateUserParams struct {
	ID           pgtype.UUID
	Username     string
	Email        string
	PasswordHash string
	Verified     bool
	Role         RoleType
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser,
		arg.ID,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
		arg.Verified,
		arg.Role,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
delete from diva_user
where id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
select
    u.id as id,
    u.username,
    u.email,
    u.password_hash as passwordHash,
    u.verified,
    u.role,
    u.created_at as createdAt,
    u.updated_at as updatedAt,
    u.deleted_at as deletedAt
from diva_user u
where u.email = $1
`

type GetUserByEmailRow struct {
	ID           pgtype.UUID
	Username     string
	Email        string
	Passwordhash string
	Verified     bool
	Role         RoleType
	Createdat    pgtype.Timestamptz
	Updatedat    pgtype.Timestamptz
	Deletedat    pgtype.Timestamptz
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Passwordhash,
		&i.Verified,
		&i.Role,
		&i.Createdat,
		&i.Updatedat,
		&i.Deletedat,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
select
    u.id as id,
    u.username,
    u.email,
    u.password_hash as passwordHash,
    u.verified,
    u.role,
    u.created_at as createdAt,
    u.updated_at as updatedAt,
    u.deleted_at as deletedAt
from diva_user u
where u.id = $1
`

type GetUserByIDRow struct {
	ID           pgtype.UUID
	Username     string
	Email        string
	Passwordhash string
	Verified     bool
	Role         RoleType
	Createdat    pgtype.Timestamptz
	Updatedat    pgtype.Timestamptz
	Deletedat    pgtype.Timestamptz
}

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Passwordhash,
		&i.Verified,
		&i.Role,
		&i.Createdat,
		&i.Updatedat,
		&i.Deletedat,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
select
    u.id as id,
    u.username,
    u.email,
    u.password_hash as passwordHash,
    u.verified,
    u.role,
    u.created_at as createdAt,
    u.updated_at as updatedAt,
    u.deleted_at as deletedAt
from diva_user u
where u.username = $1
`

type GetUserByUsernameRow struct {
	ID           pgtype.UUID
	Username     string
	Email        string
	Passwordhash string
	Verified     bool
	Role         RoleType
	Createdat    pgtype.Timestamptz
	Updatedat    pgtype.Timestamptz
	Deletedat    pgtype.Timestamptz
}

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (GetUserByUsernameRow, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i GetUserByUsernameRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Passwordhash,
		&i.Verified,
		&i.Role,
		&i.Createdat,
		&i.Updatedat,
		&i.Deletedat,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
select
    u.id as id,
    u.username,
    u.email,
    u.password_hash as passwordHash,
    u.verified,
    u.role,
    u.created_at as createdAt,
    u.updated_at as updatedAt,
    u.deleted_at as deletedAt
from diva_user u
order by u.created_at desc
`

type ListUsersRow struct {
	ID           pgtype.UUID
	Username     string
	Email        string
	Passwordhash string
	Verified     bool
	Role         RoleType
	Createdat    pgtype.Timestamptz
	Updatedat    pgtype.Timestamptz
	Deletedat    pgtype.Timestamptz
}

func (q *Queries) ListUsers(ctx context.Context) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.Passwordhash,
			&i.Verified,
			&i.Role,
			&i.Createdat,
			&i.Updatedat,
			&i.Deletedat,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreUser = `-- name: RestoreUser :exec
update diva_user
set
    deleted_at = null
where id = $1
`

func (q *Queries) RestoreUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, restoreUser, id)
	return err
}

const softDeleteUser = `-- name: SoftDeleteUser :exec
update diva_user
set
    deleted_at = now()
where id = $1
`

func (q *Queries) SoftDeleteUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteUser, id)
	return err
}

const updateEmail = `-- name: UpdateEmail :exec
update diva_user
set
    email = $1,
    updated_at = now()
where id = $2
`

type UpdateEmailParams struct {
	Email string
	ID    pgtype.UUID
}

func (q *Queries) UpdateEmail(ctx context.Context, arg UpdateEmailParams) error {
	_, err := q.db.Exec(ctx, updateEmail, arg.Email, arg.ID)
	return err
}

const updatePassword = `-- name: UpdatePassword :exec
update diva_user
set
    password_hash = $1,
    updated_at = now()
where id = $2
`

type UpdatePasswordParams struct {
	PasswordHash string
	ID           pgtype.UUID
}

func (q *Queries) UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error {
	_, err := q.db.Exec(ctx, updatePassword, arg.PasswordHash, arg.ID)
	return err
}

const updateRole = `-- name: UpdateRole :exec
update diva_user
set
    role = $1,
    updated_at = now()
where id = $2
`

type UpdateRoleParams struct {
	Role RoleType
	ID   pgtype.UUID
}

func (q *Queries) UpdateRole(ctx context.Context, arg UpdateRoleParams) error {
	_, err := q.db.Exec(ctx, updateRole, arg.Role, arg.ID)
	return err
}

const updateUsername = `-- name: UpdateUsername :exec
update diva_user
set
    username = $1,
    updated_at = now()
where id = $2
`

type UpdateUsernameParams struct {
	Username string
	ID       pgtype.UUID
}

func (q *Queries) UpdateUsername(ctx context.Context, arg UpdateUsernameParams) error {
	_, err := q.db.Exec(ctx, updateUsername, arg.Username, arg.ID)
	return err
}

const updateVerified = `-- name: UpdateVerified :exec
update diva_user
set
    verified = $1,
    updated_at = now()
where id = $2
`

type UpdateVerifiedParams struct {
	Verified bool
	ID       pgtype.UUID
}

func (q *Queries) UpdateVerified(ctx context.Context, arg UpdateVerifiedParams) error {
	_, err := q.db.Exec(ctx, updateVerified, arg.Verified, arg.ID)
	return err
}
