// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const count = `-- name: Count :one
select count(*)
from diva_user
`

func (q *Queries) Count(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, count)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO diva_user (id, email, username, password_hash, alias)
VALUES ($1, $2, $3, $4, $5)
`

type CreateUserParams struct {
	ID           pgtype.UUID
	Email        string
	Username     string
	PasswordHash string
	Alias        string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.Username,
		arg.PasswordHash,
		arg.Alias,
	)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
UPDATE diva_user 
SET deleted_at = NOW() 
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) DeleteUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getAllUsers = `-- name: GetAllUsers :many
select
    u.id,
    u.email,
    u.username,
    u.password_hash,
    u.phone_number,
    u.birth_date,
    u.alias,
    u.avatar,
    u.bio,
    u.user_verified,
    u.role,
    u.created_at,
    u.updated_at,
    u.deleted_at
from diva_user u
where u.deleted_at is null
limit $1
offset $2
`

type GetAllUsersParams struct {
	Limit  int32
	Offset int32
}

type GetAllUsersRow struct {
	ID           pgtype.UUID
	Email        string
	Username     string
	PasswordHash string
	PhoneNumber  string
	BirthDate    pgtype.Timestamptz
	Alias        string
	Avatar       string
	Bio          string
	UserVerified bool
	Role         RoleType
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	DeletedAt    pgtype.Timestamptz
}

func (q *Queries) GetAllUsers(ctx context.Context, arg GetAllUsersParams) ([]GetAllUsersRow, error) {
	rows, err := q.db.Query(ctx, getAllUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllUsersRow
	for rows.Next() {
		var i GetAllUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Username,
			&i.PasswordHash,
			&i.PhoneNumber,
			&i.BirthDate,
			&i.Alias,
			&i.Avatar,
			&i.Bio,
			&i.UserVerified,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
select
    id,
    email,
    username,
    password_hash,
    phone_number,
    birth_date,
    alias,
    avatar,
    bio,
    user_verified,
    role,
    created_at,
    updated_at,
    deleted_at
from diva_user
where email = $1 and deleted_at is null
`

type GetUserByEmailRow struct {
	ID           pgtype.UUID
	Email        string
	Username     string
	PasswordHash string
	PhoneNumber  string
	BirthDate    pgtype.Timestamptz
	Alias        string
	Avatar       string
	Bio          string
	UserVerified bool
	Role         RoleType
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	DeletedAt    pgtype.Timestamptz
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.PhoneNumber,
		&i.BirthDate,
		&i.Alias,
		&i.Avatar,
		&i.Bio,
		&i.UserVerified,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
select
    u.id,
    u.email,
    u.username,
    u.password_hash,
    u.phone_number,
    u.birth_date,
    u.alias,
    u.avatar,
    u.bio,
    u.user_verified,
    u.role,
    u.created_at,
    u.updated_at,
    u.deleted_at
from diva_user u
where u.id = $1 and u.deleted_at is null
`

type GetUserByIDRow struct {
	ID           pgtype.UUID
	Email        string
	Username     string
	PasswordHash string
	PhoneNumber  string
	BirthDate    pgtype.Timestamptz
	Alias        string
	Avatar       string
	Bio          string
	UserVerified bool
	Role         RoleType
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	DeletedAt    pgtype.Timestamptz
}

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.PhoneNumber,
		&i.BirthDate,
		&i.Alias,
		&i.Avatar,
		&i.Bio,
		&i.UserVerified,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
select
    id,
    email,
    username,
    password_hash,
    phone_number,
    birth_date,
    alias,
    avatar,
    bio,
    user_verified,
    role,
    created_at,
    updated_at,
    deleted_at
from diva_user
where username = $1 and deleted_at is null
`

type GetUserByUsernameRow struct {
	ID           pgtype.UUID
	Email        string
	Username     string
	PasswordHash string
	PhoneNumber  string
	BirthDate    pgtype.Timestamptz
	Alias        string
	Avatar       string
	Bio          string
	UserVerified bool
	Role         RoleType
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	DeletedAt    pgtype.Timestamptz
}

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (GetUserByUsernameRow, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i GetUserByUsernameRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.PhoneNumber,
		&i.BirthDate,
		&i.Alias,
		&i.Avatar,
		&i.Bio,
		&i.UserVerified,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateEmail = `-- name: UpdateEmail :exec
UPDATE diva_user
SET email = $1,
    updated_at = NOW()
WHERE id = $2 AND deleted_at IS NULL
`

type UpdateEmailParams struct {
	Email string
	ID    pgtype.UUID
}

func (q *Queries) UpdateEmail(ctx context.Context, arg UpdateEmailParams) error {
	_, err := q.db.Exec(ctx, updateEmail, arg.Email, arg.ID)
	return err
}

const updatePassword = `-- name: UpdatePassword :exec
UPDATE diva_user
SET password_hash = $1,
    updated_at = NOW()
WHERE id = $2 AND deleted_at IS NULL
`

type UpdatePasswordParams struct {
	PasswordHash string
	ID           pgtype.UUID
}

func (q *Queries) UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error {
	_, err := q.db.Exec(ctx, updatePassword, arg.PasswordHash, arg.ID)
	return err
}

const updatePhoneNumber = `-- name: UpdatePhoneNumber :exec
UPDATE diva_user
SET phone_number = $1,
    updated_at = NOW()
WHERE id = $2 AND deleted_at IS NULL
`

type UpdatePhoneNumberParams struct {
	PhoneNumber string
	ID          pgtype.UUID
}

func (q *Queries) UpdatePhoneNumber(ctx context.Context, arg UpdatePhoneNumberParams) error {
	_, err := q.db.Exec(ctx, updatePhoneNumber, arg.PhoneNumber, arg.ID)
	return err
}

const updateProfile = `-- name: UpdateProfile :exec
UPDATE diva_user 
SET alias = $1, avatar = $2, bio = $3, updated_at = NOW()
WHERE id = $4 AND deleted_at IS NULL
`

type UpdateProfileParams struct {
	Alias  string
	Avatar string
	Bio    string
	ID     pgtype.UUID
}

func (q *Queries) UpdateProfile(ctx context.Context, arg UpdateProfileParams) error {
	_, err := q.db.Exec(ctx, updateProfile,
		arg.Alias,
		arg.Avatar,
		arg.Bio,
		arg.ID,
	)
	return err
}

const updateUsername = `-- name: UpdateUsername :exec
UPDATE diva_user
SET username = $1,
    updated_at = NOW()
WHERE id = $2 AND deleted_at IS NULL
`

type UpdateUsernameParams struct {
	Username string
	ID       pgtype.UUID
}

func (q *Queries) UpdateUsername(ctx context.Context, arg UpdateUsernameParams) error {
	_, err := q.db.Exec(ctx, updateUsername, arg.Username, arg.ID)
	return err
}

const updateVerified = `-- name: UpdateVerified :exec
UPDATE diva_user
SET user_verified = $1,
    updated_at = NOW()
WHERE id = $2 AND deleted_at IS NULL
`

type UpdateVerifiedParams struct {
	UserVerified bool
	ID           pgtype.UUID
}

func (q *Queries) UpdateVerified(ctx context.Context, arg UpdateVerifiedParams) error {
	_, err := q.db.Exec(ctx, updateVerified, arg.UserVerified, arg.ID)
	return err
}
