// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqli

import (
	"database/sql"
	"time"
)

type DivaAction struct {
	ID     string
	Name   string
	UserID string
}

type DivaActionVerification struct {
	ActionID  string
	Token     string
	Verified  bool
	ExpiresAt time.Time
	UsedAt    sql.NullTime
}

type DivaPermission struct {
	ID          string
	Name        string
	Description string
	Action      string
	RoleLevel   string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	DeletedAt   sql.NullTime
}

type DivaSession struct {
	ID               string
	UserID           string
	AccessToken      string
	RefreshToken     string
	Device           string
	Type             string
	Status           string
	IpAddress        string
	UserAgent        string
	AccessExpiresAt  time.Time
	RefreshExpiresAt time.Time
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

type DivaUser struct {
	ID           string
	Username     string
	Email        string
	PhoneNumber  string
	PasswordHash string
	Role         string
	CreatedAt    time.Time
	UpdatedAt    time.Time
	DeletedAt    sql.NullTime
}

type DivaUserPermission struct {
	PermissionID string
	UserID       string
	GrantedBy    sql.NullString
	Granted      bool
	GrantedAt    time.Time
	ExpiresAt    sql.NullTime
	UpdatedAt    time.Time
}

type DivaUserPreference struct {
	ID                  string
	UserID              string
	Device              string
	Theme               string
	OnboardingCompleted bool
	Language            string
	LastSyncAt          time.Time
	CreatedAt           time.Time
	UpdatedAt           time.Time
}

type DivaUserProfile struct {
	UserID    string
	FirstName string
	LastName  string
	BirthDate sql.NullTime
	Alias     string
	Bio       string
	Avatar    string
	UpdatedAt time.Time
}

type DivaUserState struct {
	UserID       string
	Verified     bool
	Status       string
	LastActiveAt time.Time
	UpdatedAt    time.Time
}
