// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: permissions.sql

package sqli

import (
	"context"
)

const countPermissions = `-- name: CountPermissions :one
;

select count(*)
from diva_permissions
`

func (q *Queries) CountPermissions(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPermissions)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPermission = `-- name: CreatePermission :exec
;

insert into diva_permissions (
    id,
    name,
    description,
    action,
    role_level
) values (
    ?,
    ?,
    ?,
    ?,
    ?
)
`

type CreatePermissionParams struct {
	ID          string
	Name        string
	Description string
	Action      string
	RoleLevel   string
}

func (q *Queries) CreatePermission(ctx context.Context, arg CreatePermissionParams) error {
	_, err := q.db.ExecContext(ctx, createPermission,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Action,
		arg.RoleLevel,
	)
	return err
}

const deletePermission = `-- name: DeletePermission :exec
delete from diva_permissions
where id = ?
`

func (q *Queries) DeletePermission(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deletePermission, id)
	return err
}

const getPermissionByID = `-- name: GetPermissionByID :one
select
    p.id as id,
    p.name,
    p.description,
    p.action,
    p.role_level,
    p.created_at,
    p.updated_at,
    p.deleted_at
from diva_permissions p
where p.id = ?
`

func (q *Queries) GetPermissionByID(ctx context.Context, id string) (DivaPermission, error) {
	row := q.db.QueryRowContext(ctx, getPermissionByID, id)
	var i DivaPermission
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Action,
		&i.RoleLevel,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getPermissionByName = `-- name: GetPermissionByName :one
;

select
    p.id as id,
    p.name,
    p.description,
    p.action,
    p.role_level,
    p.created_at,
    p.updated_at,
    p.deleted_at
from diva_permissions p
where p.action = ?
`

func (q *Queries) GetPermissionByName(ctx context.Context, action string) (DivaPermission, error) {
	row := q.db.QueryRowContext(ctx, getPermissionByName, action)
	var i DivaPermission
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Action,
		&i.RoleLevel,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listPermissions = `-- name: ListPermissions :many
;

select
    p.id as id,
    p.name,
    p.description,
    p.action,
    p.role_level,
    p.created_at,
    p.updated_at,
    p.deleted_at
from diva_permissions p
order by p.name
limit ?
offset ?
`

type ListPermissionsParams struct {
	Limit  int64
	Offset int64
}

func (q *Queries) ListPermissions(ctx context.Context, arg ListPermissionsParams) ([]DivaPermission, error) {
	rows, err := q.db.QueryContext(ctx, listPermissions, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DivaPermission
	for rows.Next() {
		var i DivaPermission
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Action,
			&i.RoleLevel,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restorePermission = `-- name: RestorePermission :exec
update diva_permissions set
    deleted_at = null
where id = ?
`

func (q *Queries) RestorePermission(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, restorePermission, id)
	return err
}

const softDeletePermission = `-- name: SoftDeletePermission :exec
;

update diva_permissions
set
    deleted_at = CURRENT_TIMESTAMP
where id = ?
`

func (q *Queries) SoftDeletePermission(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, softDeletePermission, id)
	return err
}

const updatePermission = `-- name: UpdatePermission :exec
update diva_permissions set
    name = ?,
    description = ?,
    updated_at = CURRENT_TIMESTAMP
where id = ?
`

type UpdatePermissionParams struct {
	Name        string
	Description string
	ID          string
}

func (q *Queries) UpdatePermission(ctx context.Context, arg UpdatePermissionParams) error {
	_, err := q.db.ExecContext(ctx, updatePermission, arg.Name, arg.Description, arg.ID)
	return err
}

const updatePermissionAction = `-- name: UpdatePermissionAction :exec
update diva_permissions set
    action = ?,
    updated_at = CURRENT_TIMESTAMP
where id = ?
`

type UpdatePermissionActionParams struct {
	Action string
	ID     string
}

func (q *Queries) UpdatePermissionAction(ctx context.Context, arg UpdatePermissionActionParams) error {
	_, err := q.db.ExecContext(ctx, updatePermissionAction, arg.Action, arg.ID)
	return err
}

const updatePermissionRoleLevel = `-- name: UpdatePermissionRoleLevel :exec
update diva_permissions set
    role_level = ?,
    updated_at = CURRENT_TIMESTAMP
where id = ?
`

type UpdatePermissionRoleLevelParams struct {
	RoleLevel string
	ID        string
}

func (q *Queries) UpdatePermissionRoleLevel(ctx context.Context, arg UpdatePermissionRoleLevelParams) error {
	_, err := q.db.ExecContext(ctx, updatePermissionRoleLevel, arg.RoleLevel, arg.ID)
	return err
}
