// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: session.sql

package sqli

import (
	"context"
	"time"
)

const closeExpiredSessions = `-- name: CloseExpiredSessions :exec
;

update diva_session set
    status = 'CLOSED',
    updated_at = CURRENT_TIMESTAMP
where refresh_expires_at < CURRENT_TIMESTAMP and status != 'CLOSED'
`

func (q *Queries) CloseExpiredSessions(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, closeExpiredSessions)
	return err
}

const createSession = `-- name: CreateSession :exec
;

insert into diva_session (
    id,
    user_id,
    access_token,
    refresh_token,
    device,
    status,
    type,
    ip_address,
    user_agent,
    access_expires_at,
    refresh_expires_at
) values (
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?
)
`

type CreateSessionParams struct {
	ID               string
	UserID           string
	AccessToken      string
	RefreshToken     string
	Device           string
	Status           string
	Type             string
	IpAddress        string
	UserAgent        string
	AccessExpiresAt  time.Time
	RefreshExpiresAt time.Time
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.AccessToken,
		arg.RefreshToken,
		arg.Device,
		arg.Status,
		arg.Type,
		arg.IpAddress,
		arg.UserAgent,
		arg.AccessExpiresAt,
		arg.RefreshExpiresAt,
	)
	return err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
;

delete from diva_session
where refresh_expires_at < CURRENT_TIMESTAMP
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredSessions)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
delete from diva_session
where id = ?
`

func (q *Queries) DeleteSession(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, id)
	return err
}

const deleteSessionsByUser = `-- name: DeleteSessionsByUser :exec
;

delete from diva_session
where user_id = ?
`

func (q *Queries) DeleteSessionsByUser(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, deleteSessionsByUser, userID)
	return err
}

const getSessionByID = `-- name: GetSessionByID :one
select
    s.id,
    s.user_id,
    s.access_token,
    s.refresh_token,
    s.device,
    s.type,
    s.status,
    s.ip_address,
    s.user_agent,
    s.access_expires_at,
    s.refresh_expires_at,
    s.created_at,
    s.updated_at
from diva_session s
where s.id = ?
`

func (q *Queries) GetSessionByID(ctx context.Context, id string) (DivaSession, error) {
	row := q.db.QueryRowContext(ctx, getSessionByID, id)
	var i DivaSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccessToken,
		&i.RefreshToken,
		&i.Device,
		&i.Type,
		&i.Status,
		&i.IpAddress,
		&i.UserAgent,
		&i.AccessExpiresAt,
		&i.RefreshExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSessionsByUser = `-- name: ListSessionsByUser :many
;

select
    s.id,
    s.user_id,
    s.access_token,
    s.refresh_token,
    s.device,
    s.type,
    s.status,
    s.ip_address,
    s.user_agent,
    s.access_expires_at,
    s.refresh_expires_at,
    s.created_at,
    s.updated_at
from diva_session s
where s.user_id = ?
order by created_at desc
`

func (q *Queries) ListSessionsByUser(ctx context.Context, userID string) ([]DivaSession, error) {
	rows, err := q.db.QueryContext(ctx, listSessionsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DivaSession
	for rows.Next() {
		var i DivaSession
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AccessToken,
			&i.RefreshToken,
			&i.Device,
			&i.Type,
			&i.Status,
			&i.IpAddress,
			&i.UserAgent,
			&i.AccessExpiresAt,
			&i.RefreshExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSession = `-- name: UpdateSession :exec
update diva_session set
    access_token = ?,
    refresh_token = ?,
    ip_address = ?,
    access_expires_at = ?,
    refresh_expires_at = ?,
    updated_at = CURRENT_TIMESTAMP
where id = ?
`

type UpdateSessionParams struct {
	AccessToken      string
	RefreshToken     string
	IpAddress        string
	AccessExpiresAt  time.Time
	RefreshExpiresAt time.Time
	ID               string
}

func (q *Queries) UpdateSession(ctx context.Context, arg UpdateSessionParams) error {
	_, err := q.db.ExecContext(ctx, updateSession,
		arg.AccessToken,
		arg.RefreshToken,
		arg.IpAddress,
		arg.AccessExpiresAt,
		arg.RefreshExpiresAt,
		arg.ID,
	)
	return err
}

const updateSessionStatus = `-- name: UpdateSessionStatus :exec
update diva_session set
    status = ?,
    updated_at = CURRENT_TIMESTAMP
where id = ?
`

type UpdateSessionStatusParams struct {
	Status string
	ID     string
}

func (q *Queries) UpdateSessionStatus(ctx context.Context, arg UpdateSessionStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateSessionStatus, arg.Status, arg.ID)
	return err
}
