// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_action.sql

package sqli

import (
	"context"
)

const createUserAction = `-- name: CreateUserAction :exec
;

insert into diva_action (
    id,
    name,
    user_id
) values (
    ?,
    ?,
    ?
)
`

type CreateUserActionParams struct {
	ID     string
	Name   string
	UserID string
}

func (q *Queries) CreateUserAction(ctx context.Context, arg CreateUserActionParams) error {
	_, err := q.db.ExecContext(ctx, createUserAction, arg.ID, arg.Name, arg.UserID)
	return err
}

const deleteUserAction = `-- name: DeleteUserAction :exec
delete from diva_action
where id = ?
`

func (q *Queries) DeleteUserAction(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteUserAction, id)
	return err
}

const deleteUserActionByUser = `-- name: DeleteUserActionByUser :exec
;

delete from diva_action
where user_id = ?
`

func (q *Queries) DeleteUserActionByUser(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, deleteUserActionByUser, userID)
	return err
}

const getUserActionByID = `-- name: GetUserActionByID :one
;

select ua.id, ua.name, ua.user_id
from diva_action ua
where ua.id = ?
`

func (q *Queries) GetUserActionByID(ctx context.Context, id string) (DivaAction, error) {
	row := q.db.QueryRowContext(ctx, getUserActionByID, id)
	var i DivaAction
	err := row.Scan(&i.ID, &i.Name, &i.UserID)
	return i, err
}

const getUserActionByUserAndName = `-- name: GetUserActionByUserAndName :one
;

select ua.id, ua.name, ua.user_id
from diva_action ua
where ua.user_id = ? and ua.name = ?
`

type GetUserActionByUserAndNameParams struct {
	UserID string
	Name   string
}

func (q *Queries) GetUserActionByUserAndName(ctx context.Context, arg GetUserActionByUserAndNameParams) (DivaAction, error) {
	row := q.db.QueryRowContext(ctx, getUserActionByUserAndName, arg.UserID, arg.Name)
	var i DivaAction
	err := row.Scan(&i.ID, &i.Name, &i.UserID)
	return i, err
}

const listActionsByUser = `-- name: ListActionsByUser :many
select ua.id, ua.name, ua.user_id
from diva_action ua
where ua.user_id = ?
`

func (q *Queries) ListActionsByUser(ctx context.Context, userID string) ([]DivaAction, error) {
	rows, err := q.db.QueryContext(ctx, listActionsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DivaAction
	for rows.Next() {
		var i DivaAction
		if err := rows.Scan(&i.ID, &i.Name, &i.UserID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
