// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_profile.sql

package sqli

import (
	"context"
	"database/sql"
)

const createUserProfile = `-- name: CreateUserProfile :exec
;

insert into diva_user_profile (
    user_id,
    first_name,
    last_name,
    birth_date,
    alias,
    bio
) values (
    ?,
    ?,
    ?,
    ?,
    ?,
    ?
)
`

type CreateUserProfileParams struct {
	UserID    string
	FirstName string
	LastName  string
	BirthDate sql.NullTime
	Alias     string
	Bio       string
}

func (q *Queries) CreateUserProfile(ctx context.Context, arg CreateUserProfileParams) error {
	_, err := q.db.ExecContext(ctx, createUserProfile,
		arg.UserID,
		arg.FirstName,
		arg.LastName,
		arg.BirthDate,
		arg.Alias,
		arg.Bio,
	)
	return err
}

const getUserProfileByUserID = `-- name: GetUserProfileByUserID :one
select
    up.user_id,
    up.first_name,
    up.last_name,
    up.birth_date,
    up.alias,
    up.bio,
    up.avatar,
    up.updated_at
from diva_user_profile up
where up.user_id = ?
`

func (q *Queries) GetUserProfileByUserID(ctx context.Context, userID string) (DivaUserProfile, error) {
	row := q.db.QueryRowContext(ctx, getUserProfileByUserID, userID)
	var i DivaUserProfile
	err := row.Scan(
		&i.UserID,
		&i.FirstName,
		&i.LastName,
		&i.BirthDate,
		&i.Alias,
		&i.Bio,
		&i.Avatar,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserProfile = `-- name: UpdateUserProfile :exec
update diva_user_profile set
    first_name = ?,
    last_name = ?,
    birth_date = ?,
    alias = ?,
    bio = ?,
    updated_at = CURRENT_TIMESTAMP
where user_id = ?
`

type UpdateUserProfileParams struct {
	FirstName string
	LastName  string
	BirthDate sql.NullTime
	Alias     string
	Bio       string
	UserID    string
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) error {
	_, err := q.db.ExecContext(ctx, updateUserProfile,
		arg.FirstName,
		arg.LastName,
		arg.BirthDate,
		arg.Alias,
		arg.Bio,
		arg.UserID,
	)
	return err
}

const updateUserProfileAvatar = `-- name: UpdateUserProfileAvatar :exec
update diva_user_profile set
    avatar = ?,
    updated_at = CURRENT_TIMESTAMP
where user_id = ?
`

type UpdateUserProfileAvatarParams struct {
	Avatar string
	UserID string
}

func (q *Queries) UpdateUserProfileAvatar(ctx context.Context, arg UpdateUserProfileAvatarParams) error {
	_, err := q.db.ExecContext(ctx, updateUserProfileAvatar, arg.Avatar, arg.UserID)
	return err
}
