// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_verification.sql

package sqli

import (
	"context"
	"database/sql"
	"time"
)

const createUserVerification = `-- name: CreateUserVerification :exec
;

insert into diva_action_verification (
    action_id,
    token,
    expires_at
) values (
    ?,
    ?,
    ?
)
`

type CreateUserVerificationParams struct {
	ActionID  string
	Token     string
	ExpiresAt time.Time
}

func (q *Queries) CreateUserVerification(ctx context.Context, arg CreateUserVerificationParams) error {
	_, err := q.db.ExecContext(ctx, createUserVerification, arg.ActionID, arg.Token, arg.ExpiresAt)
	return err
}

const deleteUserVerification = `-- name: DeleteUserVerification :exec
delete from diva_action_verification
where action_id = ?
`

func (q *Queries) DeleteUserVerification(ctx context.Context, actionID string) error {
	_, err := q.db.ExecContext(ctx, deleteUserVerification, actionID)
	return err
}

const getUserVerification = `-- name: GetUserVerification :one
select v.action_id, v.token, v.expires_at, v.used_at, v.verified
from diva_action_verification v
where v.action_id = ?
`

type GetUserVerificationRow struct {
	ActionID  string
	Token     string
	ExpiresAt time.Time
	UsedAt    sql.NullTime
	Verified  bool
}

func (q *Queries) GetUserVerification(ctx context.Context, actionID string) (GetUserVerificationRow, error) {
	row := q.db.QueryRowContext(ctx, getUserVerification, actionID)
	var i GetUserVerificationRow
	err := row.Scan(
		&i.ActionID,
		&i.Token,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.Verified,
	)
	return i, err
}

const updateUserVerification = `-- name: UpdateUserVerification :exec
update diva_action_verification set
    verified = ?,
    used_at = CURRENT_TIMESTAMP
where action_id = ?
`

type UpdateUserVerificationParams struct {
	Verified bool
	ActionID string
}

func (q *Queries) UpdateUserVerification(ctx context.Context, arg UpdateUserVerificationParams) error {
	_, err := q.db.ExecContext(ctx, updateUserVerification, arg.Verified, arg.ActionID)
	return err
}
