// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_preferences.sql

package sqli

import (
	"context"
)

const createUserPreferences = `-- name: CreateUserPreferences :exec
;

insert into diva_user_preferences (
    id,
    user_id,
    device,
    theme,
    onboarding_completed,
    language
) values (
    ?,
    ?,
    ?,
    ?,
    ?,
    ?
)
`

type CreateUserPreferencesParams struct {
	ID                  string
	UserID              string
	Device              string
	Theme               string
	OnboardingCompleted bool
	Language            string
}

func (q *Queries) CreateUserPreferences(ctx context.Context, arg CreateUserPreferencesParams) error {
	_, err := q.db.ExecContext(ctx, createUserPreferences,
		arg.ID,
		arg.UserID,
		arg.Device,
		arg.Theme,
		arg.OnboardingCompleted,
		arg.Language,
	)
	return err
}

const getPreferencesByID = `-- name: GetPreferencesByID :one
select
    up.id as id,
    up.user_id,
    up.device,
    up.theme,
    up.onboarding_completed,
    up.language,
    up.last_sync_at,
    up.created_at,
    up.updated_at
from diva_user_preferences up
where up.id = ?
`

func (q *Queries) GetPreferencesByID(ctx context.Context, id string) (DivaUserPreference, error) {
	row := q.db.QueryRowContext(ctx, getPreferencesByID, id)
	var i DivaUserPreference
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Device,
		&i.Theme,
		&i.OnboardingCompleted,
		&i.Language,
		&i.LastSyncAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPreferencesByUser = `-- name: GetPreferencesByUser :many
;

select
    up.id as id,
    up.user_id,
    up.device,
    up.theme,
    up.onboarding_completed,
    up.language,
    up.last_sync_at,
    up.created_at,
    up.updated_at
from diva_user_preferences up
where up.user_id = ?
`

func (q *Queries) GetPreferencesByUser(ctx context.Context, userID string) ([]DivaUserPreference, error) {
	rows, err := q.db.QueryContext(ctx, getPreferencesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DivaUserPreference
	for rows.Next() {
		var i DivaUserPreference
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Device,
			&i.Theme,
			&i.OnboardingCompleted,
			&i.Language,
			&i.LastSyncAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserPreferences = `-- name: UpdateUserPreferences :exec
update diva_user_preferences set
    theme = ?,
    language = ?,
    last_sync_at = CURRENT_TIMESTAMP,
    updated_at = CURRENT_TIMESTAMP
where id = ?
`

type UpdateUserPreferencesParams struct {
	Theme    string
	Language string
	ID       string
}

func (q *Queries) UpdateUserPreferences(ctx context.Context, arg UpdateUserPreferencesParams) error {
	_, err := q.db.ExecContext(ctx, updateUserPreferences, arg.Theme, arg.Language, arg.ID)
	return err
}
