// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_status.sql

package sqli

import (
	"context"
)

const createUserState = `-- name: CreateUserState :exec
;

insert into diva_user_state (
    user_id,
    verified,
    status
) values (
    ?,
    ?,
    ?
)
`

type CreateUserStateParams struct {
	UserID   string
	Verified bool
	Status   string
}

func (q *Queries) CreateUserState(ctx context.Context, arg CreateUserStateParams) error {
	_, err := q.db.ExecContext(ctx, createUserState, arg.UserID, arg.Verified, arg.Status)
	return err
}

const getUserStateByUserID = `-- name: GetUserStateByUserID :one
select us.user_id, us.verified, us.status, us.last_active_at, us.updated_at
from diva_user_state us
where us.user_id = ?
`

func (q *Queries) GetUserStateByUserID(ctx context.Context, userID string) (DivaUserState, error) {
	row := q.db.QueryRowContext(ctx, getUserStateByUserID, userID)
	var i DivaUserState
	err := row.Scan(
		&i.UserID,
		&i.Verified,
		&i.Status,
		&i.LastActiveAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateLastActiveAt = `-- name: UpdateLastActiveAt :exec
update diva_user_state set
    last_active_at = CURRENT_TIMESTAMP,
    updated_at = CURRENT_TIMESTAMP
where user_id = ?
`

func (q *Queries) UpdateLastActiveAt(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, updateLastActiveAt, userID)
	return err
}

const updateUserStatus = `-- name: UpdateUserStatus :exec
update diva_user_state set
    status = ?,
    updated_at = CURRENT_TIMESTAMP
where user_id = ?
`

type UpdateUserStatusParams struct {
	Status string
	UserID string
}

func (q *Queries) UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateUserStatus, arg.Status, arg.UserID)
	return err
}

const updateUserVerified = `-- name: UpdateUserVerified :exec
update diva_user_state set
    verified = ?,
    updated_at = CURRENT_TIMESTAMP
where user_id = ?
`

type UpdateUserVerifiedParams struct {
	Verified bool
	UserID   string
}

func (q *Queries) UpdateUserVerified(ctx context.Context, arg UpdateUserVerifiedParams) error {
	_, err := q.db.ExecContext(ctx, updateUserVerified, arg.Verified, arg.UserID)
	return err
}
