// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user.sql

package sqli

import (
	"context"
)

const countUsers = `-- name: CountUsers :one
;

select count(*)
from diva_user
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :exec
;

insert into diva_user (
    id,
    username,
    email,
    password_hash,
    role
) values (
    ?,
    ?,
    ?,
    ?,
    ?
)
`

type CreateUserParams struct {
	ID           string
	Username     string
	Email        string
	PasswordHash string
	Role         string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser,
		arg.ID,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
		arg.Role,
	)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
delete from diva_user
where id = ?
`

func (q *Queries) DeleteUser(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
;

select
    u.id as id,
    u.username,
    u.email,
    u.phone_number,
    u.password_hash,
    u.role,
    u.created_at,
    u.updated_at,
    u.deleted_at
from diva_user u
where u.email = ?
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (DivaUser, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i DivaUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PhoneNumber,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
select
    u.id as id,
    u.username,
    u.email,
    u.phone_number,
    u.password_hash,
    u.role,
    u.created_at,
    u.updated_at,
    u.deleted_at
from diva_user u
where u.id = ?
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (DivaUser, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i DivaUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PhoneNumber,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
;

select
    u.id as id,
    u.username,
    u.email,
    u.phone_number,
    u.password_hash,
    u.role,
    u.created_at,
    u.updated_at,
    u.deleted_at
from diva_user u
where u.username = ?
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (DivaUser, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i DivaUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PhoneNumber,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByUsernameOrEmail = `-- name: GetUserByUsernameOrEmail :one
;

select
    u.id as id,
    u.username,
    u.email,
    u.phone_number,
    u.password_hash,
    u.role,
    u.created_at,
    u.updated_at,
    u.deleted_at
from diva_user u
where u.email = ? or u.username = ?
`

type GetUserByUsernameOrEmailParams struct {
	Email    string
	Username string
}

func (q *Queries) GetUserByUsernameOrEmail(ctx context.Context, arg GetUserByUsernameOrEmailParams) (DivaUser, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsernameOrEmail, arg.Email, arg.Username)
	var i DivaUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PhoneNumber,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
;

select
    u.id as id,
    u.username,
    u.email,
    u.phone_number,
    u.password_hash,
    u.role,
    u.created_at,
    u.updated_at,
    u.deleted_at
from diva_user u
order by u.created_at desc
limit ?
offset ?
`

type ListUsersParams struct {
	Limit  int64
	Offset int64
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]DivaUser, error) {
	rows, err := q.db.QueryContext(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DivaUser
	for rows.Next() {
		var i DivaUser
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.PhoneNumber,
			&i.PasswordHash,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreUser = `-- name: RestoreUser :exec
update diva_user set
    deleted_at = null,
    updated_at = CURRENT_TIMESTAMP
where id = ?
`

func (q *Queries) RestoreUser(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, restoreUser, id)
	return err
}

const softDeleteUser = `-- name: SoftDeleteUser :exec
;

update diva_user set
    deleted_at = CURRENT_TIMESTAMP
where id = ?
`

func (q *Queries) SoftDeleteUser(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, softDeleteUser, id)
	return err
}

const updateEmail = `-- name: UpdateEmail :exec
update diva_user set
    email = ?,
    updated_at = CURRENT_TIMESTAMP
where id = ?
`

type UpdateEmailParams struct {
	Email string
	ID    string
}

func (q *Queries) UpdateEmail(ctx context.Context, arg UpdateEmailParams) error {
	_, err := q.db.ExecContext(ctx, updateEmail, arg.Email, arg.ID)
	return err
}

const updatePassword = `-- name: UpdatePassword :exec
update diva_user set
    password_hash = ?,
    updated_at = CURRENT_TIMESTAMP
where id = ?
`

type UpdatePasswordParams struct {
	PasswordHash string
	ID           string
}

func (q *Queries) UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error {
	_, err := q.db.ExecContext(ctx, updatePassword, arg.PasswordHash, arg.ID)
	return err
}

const updatePhoneNumber = `-- name: UpdatePhoneNumber :exec
update diva_user set
    phone_number = ?,
    updated_at = CURRENT_TIMESTAMP
where id = ?
`

type UpdatePhoneNumberParams struct {
	PhoneNumber string
	ID          string
}

func (q *Queries) UpdatePhoneNumber(ctx context.Context, arg UpdatePhoneNumberParams) error {
	_, err := q.db.ExecContext(ctx, updatePhoneNumber, arg.PhoneNumber, arg.ID)
	return err
}

const updateRole = `-- name: UpdateRole :exec
update diva_user set
    role = ?,
    updated_at = CURRENT_TIMESTAMP
where id = ?
`

type UpdateRoleParams struct {
	Role string
	ID   string
}

func (q *Queries) UpdateRole(ctx context.Context, arg UpdateRoleParams) error {
	_, err := q.db.ExecContext(ctx, updateRole, arg.Role, arg.ID)
	return err
}

const updateUsername = `-- name: UpdateUsername :exec
update diva_user set
    username = ?,
    updated_at = CURRENT_TIMESTAMP
where id = ?
`

type UpdateUsernameParams struct {
	Username string
	ID       string
}

func (q *Queries) UpdateUsername(ctx context.Context, arg UpdateUsernameParams) error {
	_, err := q.db.ExecContext(ctx, updateUsername, arg.Username, arg.ID)
	return err
}
