// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_permissions.sql

package sqli

import (
	"context"
	"database/sql"
)

const createUserPermission = `-- name: CreateUserPermission :exec
;

insert into diva_user_permissions (
    permission_id,
    user_id,
    granted_by,
    granted,
    expires_at
) values (
    ?,
    ?,
    ?,
    ?,
    ?
)
`

type CreateUserPermissionParams struct {
	PermissionID string
	UserID       string
	GrantedBy    sql.NullString
	Granted      bool
	ExpiresAt    sql.NullTime
}

func (q *Queries) CreateUserPermission(ctx context.Context, arg CreateUserPermissionParams) error {
	_, err := q.db.ExecContext(ctx, createUserPermission,
		arg.PermissionID,
		arg.UserID,
		arg.GrantedBy,
		arg.Granted,
		arg.ExpiresAt,
	)
	return err
}

const deleteExpiredUserPermissions = `-- name: DeleteExpiredUserPermissions :exec
;

delete from diva_user_permissions
where expires_at is not null and expires_at < CURRENT_TIMESTAMP
`

func (q *Queries) DeleteExpiredUserPermissions(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredUserPermissions)
	return err
}

const deleteUserPermission = `-- name: DeleteUserPermission :exec
delete from diva_user_permissions
where permission_id = ? and user_id = ?
`

type DeleteUserPermissionParams struct {
	PermissionID string
	UserID       string
}

func (q *Queries) DeleteUserPermission(ctx context.Context, arg DeleteUserPermissionParams) error {
	_, err := q.db.ExecContext(ctx, deleteUserPermission, arg.PermissionID, arg.UserID)
	return err
}

const getUserPermission = `-- name: GetUserPermission :one
;

select
    up.permission_id,
    up.user_id,
    up.granted_by,
    up.granted,
    up.granted_at,
    up.expires_at,
    up.updated_at
from diva_user_permissions up
where up.permission_id = ? and up.user_id = ?
`

type GetUserPermissionParams struct {
	PermissionID string
	UserID       string
}

func (q *Queries) GetUserPermission(ctx context.Context, arg GetUserPermissionParams) (DivaUserPermission, error) {
	row := q.db.QueryRowContext(ctx, getUserPermission, arg.PermissionID, arg.UserID)
	var i DivaUserPermission
	err := row.Scan(
		&i.PermissionID,
		&i.UserID,
		&i.GrantedBy,
		&i.Granted,
		&i.GrantedAt,
		&i.ExpiresAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserPermissionByName = `-- name: GetUserPermissionByName :one
;

select
    up.permission_id,
    up.user_id,
    up.granted_by,
    up.granted,
    up.granted_at,
    up.expires_at,
    up.updated_at
from diva_user_permissions up
left join diva_permissions dp on up.permission_id = dp.id
where up.user_id = ? and dp.name = ?
`

type GetUserPermissionByNameParams struct {
	UserID string
	Name   string
}

func (q *Queries) GetUserPermissionByName(ctx context.Context, arg GetUserPermissionByNameParams) (DivaUserPermission, error) {
	row := q.db.QueryRowContext(ctx, getUserPermissionByName, arg.UserID, arg.Name)
	var i DivaUserPermission
	err := row.Scan(
		&i.PermissionID,
		&i.UserID,
		&i.GrantedBy,
		&i.Granted,
		&i.GrantedAt,
		&i.ExpiresAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserPermissions = `-- name: GetUserPermissions :many
select
    up.permission_id,
    up.user_id,
    up.granted_by,
    up.granted,
    up.granted_at,
    up.expires_at,
    up.updated_at
from diva_user_permissions up
where up.user_id = ? and up.granted = true
`

func (q *Queries) GetUserPermissions(ctx context.Context, userID string) ([]DivaUserPermission, error) {
	rows, err := q.db.QueryContext(ctx, getUserPermissions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DivaUserPermission
	for rows.Next() {
		var i DivaUserPermission
		if err := rows.Scan(
			&i.PermissionID,
			&i.UserID,
			&i.GrantedBy,
			&i.Granted,
			&i.GrantedAt,
			&i.ExpiresAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserPermission = `-- name: UpdateUserPermission :exec
;

update diva_user_permissions
set
    granted = ?,
    expires_at = ?,
    updated_at = CURRENT_TIMESTAMP
where permission_id = ? and user_id = ?
`

type UpdateUserPermissionParams struct {
	Granted      bool
	ExpiresAt    sql.NullTime
	PermissionID string
	UserID       string
}

func (q *Queries) UpdateUserPermission(ctx context.Context, arg UpdateUserPermissionParams) error {
	_, err := q.db.ExecContext(ctx, updateUserPermission,
		arg.Granted,
		arg.ExpiresAt,
		arg.PermissionID,
		arg.UserID,
	)
	return err
}
