// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package pg

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type MediaTypeType string

const (
	MediaTypeTypeAUDIO       MediaTypeType = "AUDIO"
	MediaTypeTypeIMAGE       MediaTypeType = "IMAGE"
	MediaTypeTypeVIDEO       MediaTypeType = "VIDEO"
	MediaTypeTypeUNSPECIFIED MediaTypeType = "UNSPECIFIED"
)

func (e *MediaTypeType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MediaTypeType(s)
	case string:
		*e = MediaTypeType(s)
	default:
		return fmt.Errorf("unsupported scan type for MediaTypeType: %T", src)
	}
	return nil
}

type NullMediaTypeType struct {
	MediaTypeType MediaTypeType
	Valid         bool // Valid is true if MediaTypeType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMediaTypeType) Scan(value interface{}) error {
	if value == nil {
		ns.MediaTypeType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MediaTypeType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMediaTypeType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MediaTypeType), nil
}

type RoleType string

const (
	RoleTypeUSER      RoleType = "USER"
	RoleTypeMODERATOR RoleType = "MODERATOR"
	RoleTypeADMIN     RoleType = "ADMIN"
)

func (e *RoleType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RoleType(s)
	case string:
		*e = RoleType(s)
	default:
		return fmt.Errorf("unsupported scan type for RoleType: %T", src)
	}
	return nil
}

type NullRoleType struct {
	RoleType RoleType
	Valid    bool // Valid is true if RoleType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRoleType) Scan(value interface{}) error {
	if value == nil {
		ns.RoleType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RoleType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRoleType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RoleType), nil
}

type SessionStatusType string

const (
	SessionStatusTypeACTIVE  SessionStatusType = "ACTIVE"
	SessionStatusTypeEXPIRED SessionStatusType = "EXPIRED"
	SessionStatusTypeCLOSED  SessionStatusType = "CLOSED"
)

func (e *SessionStatusType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SessionStatusType(s)
	case string:
		*e = SessionStatusType(s)
	default:
		return fmt.Errorf("unsupported scan type for SessionStatusType: %T", src)
	}
	return nil
}

type NullSessionStatusType struct {
	SessionStatusType SessionStatusType
	Valid             bool // Valid is true if SessionStatusType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSessionStatusType) Scan(value interface{}) error {
	if value == nil {
		ns.SessionStatusType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SessionStatusType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSessionStatusType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SessionStatusType), nil
}

type SessionType string

const (
	SessionTypeNORMAL   SessionType = "NORMAL"
	SessionTypeTEMPORAL SessionType = "TEMPORAL"
)

func (e *SessionType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SessionType(s)
	case string:
		*e = SessionType(s)
	default:
		return fmt.Errorf("unsupported scan type for SessionType: %T", src)
	}
	return nil
}

type NullSessionType struct {
	SessionType SessionType
	Valid       bool // Valid is true if SessionType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSessionType) Scan(value interface{}) error {
	if value == nil {
		ns.SessionType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SessionType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSessionType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SessionType), nil
}

type ThemeType string

const (
	ThemeTypeLIGHT  ThemeType = "LIGHT"
	ThemeTypeDARK   ThemeType = "DARK"
	ThemeTypeSYSTEM ThemeType = "SYSTEM"
)

func (e *ThemeType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ThemeType(s)
	case string:
		*e = ThemeType(s)
	default:
		return fmt.Errorf("unsupported scan type for ThemeType: %T", src)
	}
	return nil
}

type NullThemeType struct {
	ThemeType ThemeType
	Valid     bool // Valid is true if ThemeType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullThemeType) Scan(value interface{}) error {
	if value == nil {
		ns.ThemeType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ThemeType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullThemeType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ThemeType), nil
}

type UserStatusType string

const (
	UserStatusTypeACTIVE    UserStatusType = "ACTIVE"
	UserStatusTypeSUSPENDED UserStatusType = "SUSPENDED"
	UserStatusTypeINACTIVE  UserStatusType = "INACTIVE"
)

func (e *UserStatusType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserStatusType(s)
	case string:
		*e = UserStatusType(s)
	default:
		return fmt.Errorf("unsupported scan type for UserStatusType: %T", src)
	}
	return nil
}

type NullUserStatusType struct {
	UserStatusType UserStatusType
	Valid          bool // Valid is true if UserStatusType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserStatusType) Scan(value interface{}) error {
	if value == nil {
		ns.UserStatusType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserStatusType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserStatusType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserStatusType), nil
}

type DivaAction struct {
	ID     pgtype.UUID
	Name   string
	UserID pgtype.UUID
}

type DivaActionVerification struct {
	ActionID  pgtype.UUID
	Token     string
	Verified  bool
	ExpiresAt pgtype.Timestamptz
	UsedAt    pgtype.Timestamptz
}

type DivaPermission struct {
	ID          pgtype.UUID
	Name        string
	Description string
	Action      string
	RoleLevel   RoleType
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	DeletedAt   pgtype.Timestamptz
}

type DivaSession struct {
	ID               pgtype.UUID
	UserID           pgtype.UUID
	AccessToken      string
	RefreshToken     string
	Device           string
	Type             SessionType
	Status           SessionStatusType
	IpAddress        string
	UserAgent        string
	AccessExpiresAt  pgtype.Timestamptz
	RefreshExpiresAt pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type DivaUser struct {
	ID           pgtype.UUID
	Username     string
	Email        string
	PhoneNumber  string
	PasswordHash string
	Role         RoleType
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	DeletedAt    pgtype.Timestamptz
}

type DivaUserPermission struct {
	PermissionID pgtype.UUID
	UserID       pgtype.UUID
	GrantedBy    pgtype.UUID
	Granted      bool
	GrantedAt    pgtype.Timestamptz
	ExpiresAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type DivaUserPreference struct {
	ID                  pgtype.UUID
	UserID              pgtype.UUID
	Device              string
	Theme               ThemeType
	OnboardingCompleted bool
	Language            string
	LastSyncAt          pgtype.Timestamptz
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
}

type DivaUserProfile struct {
	UserID    pgtype.UUID
	FirstName string
	LastName  string
	BirthDate pgtype.Timestamptz
	Alias     string
	Bio       string
	Avatar    string
	UpdatedAt pgtype.Timestamptz
}

type DivaUserState struct {
	UserID       pgtype.UUID
	Verified     bool
	Status       UserStatusType
	LastActiveAt pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}
