// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: session.sql

package pg

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :exec
insert into diva_session (
    id,
    user_id,
    access_token,
    refresh_token,
    device,
    status,
    type,
    ip_address,
    user_agent,
    access_expires_at,
    refresh_expires_at
) values (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11
)
`

type CreateSessionParams struct {
	ID               pgtype.UUID
	UserID           pgtype.UUID
	AccessToken      string
	RefreshToken     string
	Device           string
	Status           SessionStatusType
	Type             SessionType
	IpAddress        string
	UserAgent        string
	AccessExpiresAt  pgtype.Timestamptz
	RefreshExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.AccessToken,
		arg.RefreshToken,
		arg.Device,
		arg.Status,
		arg.Type,
		arg.IpAddress,
		arg.UserAgent,
		arg.AccessExpiresAt,
		arg.RefreshExpiresAt,
	)
	return err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
delete from diva_session
where refresh_expires_at < now()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredSessions)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
delete from diva_session
where id = $1
`

func (q *Queries) DeleteSession(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSession, id)
	return err
}

const deleteSessionsByUser = `-- name: DeleteSessionsByUser :exec
delete from diva_session
where user_id = $1
`

func (q *Queries) DeleteSessionsByUser(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSessionsByUser, userID)
	return err
}

const getSessionByID = `-- name: GetSessionByID :one
select
    s.id,
    s.user_id,
    s.access_token,
    s.refresh_token,
    s.device,
    s.type,
    s.status,
    s.ip_address,
    s.user_agent,
    s.access_expires_at,
    s.refresh_expires_at,
    s.created_at,
    s.updated_at
from diva_session s
where s.id = $1
`

func (q *Queries) GetSessionByID(ctx context.Context, id pgtype.UUID) (DivaSession, error) {
	row := q.db.QueryRow(ctx, getSessionByID, id)
	var i DivaSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccessToken,
		&i.RefreshToken,
		&i.Device,
		&i.Type,
		&i.Status,
		&i.IpAddress,
		&i.UserAgent,
		&i.AccessExpiresAt,
		&i.RefreshExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSessionsByUser = `-- name: ListSessionsByUser :many
select
    s.id,
    s.user_id,
    s.access_token,
    s.refresh_token,
    s.device,
    s.type,
    s.status,
    s.ip_address,
    s.user_agent,
    s.access_expires_at,
    s.refresh_expires_at,
    s.created_at,
    s.updated_at
from diva_session s
where s.user_id = $1
order by created_at desc
`

func (q *Queries) ListSessionsByUser(ctx context.Context, userID pgtype.UUID) ([]DivaSession, error) {
	rows, err := q.db.Query(ctx, listSessionsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DivaSession
	for rows.Next() {
		var i DivaSession
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AccessToken,
			&i.RefreshToken,
			&i.Device,
			&i.Type,
			&i.Status,
			&i.IpAddress,
			&i.UserAgent,
			&i.AccessExpiresAt,
			&i.RefreshExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSession = `-- name: UpdateSession :exec
update diva_session set
    access_token = $1,
    refresh_token = $2,
    ip_address = $3,
    access_expires_at = $4,
    refresh_expires_at = $5,
    updated_at = now()
where id = $6
`

type UpdateSessionParams struct {
	AccessToken      string
	RefreshToken     string
	IpAddress        string
	AccessExpiresAt  pgtype.Timestamptz
	RefreshExpiresAt pgtype.Timestamptz
	ID               pgtype.UUID
}

func (q *Queries) UpdateSession(ctx context.Context, arg UpdateSessionParams) error {
	_, err := q.db.Exec(ctx, updateSession,
		arg.AccessToken,
		arg.RefreshToken,
		arg.IpAddress,
		arg.AccessExpiresAt,
		arg.RefreshExpiresAt,
		arg.ID,
	)
	return err
}

const updateSessionStatus = `-- name: UpdateSessionStatus :exec
update diva_session set
    status = $1,
    updated_at = now()
where id = $2
`

type UpdateSessionStatusParams struct {
	Status SessionStatusType
	ID     pgtype.UUID
}

func (q *Queries) UpdateSessionStatus(ctx context.Context, arg UpdateSessionStatusParams) error {
	_, err := q.db.Exec(ctx, updateSessionStatus, arg.Status, arg.ID)
	return err
}
